### ISSUE TITLE
Graceful Shutdown not waiting for context timeout 

### ISSUE THREAD

**Issue by farrukhny** [ardanlabs/service#100]
Graceful shutdown not waiting for grace period and exit from app. I have increased timeout to 150s but it is exits out immediately

![Screen Shot 2019-07-30 at 1 48 59 PM](https://user-images.githubusercontent.com/6372846/62153042-bf5d9100-b2d1-11e9-8e5a-72dc62c5af74.png)

stopping app with Ctrl + C on Mac terminal.

**Comment by jcbwlkr** [comment]
The timeout is a **maximum** time that the server will wait to shut down gracefully. If there is no traffic to the server then it can exit immediately and it will.

**Comment by farrukhny** [comment]
I actually test it with a requests maybe not the right way i am using wrk to send a request to health check endpoint 


![Screen Shot 2019-07-30 at 2 05 53 PM](https://user-images.githubusercontent.com/6372846/62153778-52e39180-b2d3-11e9-967c-dfc2c5c12820.png)


I have send a lot of request

**Comment by jcbwlkr** [comment]
When you hit ctrl-c the server stops taking new requests and puts a maximum time it will wait for current requests to finish. If you want to see the server actually time out you have to make a request an endpoint that takes longer to complete (or put a time.Sleep in an existing endpoint to make it be slow)

**Comment by ardan-bkennedy** [comment]
has this been resolved or does it need more discussion?
