### ISSUE TITLE
Proposal: Keys generation

### ISSUE THREAD

**Issue by rjtch** [ardanlabs/service#101]
It is normaly not an issue but just to my point of view a simple recomendation. To build the project a private key private.pem should be provided so in the makefile it would be better maybe to generate the private key automatically.
My example in the makefile

`all: keys sales-api metrics up `

**Comment by ardan-bkennedy** [comment]
Send me an email so we can talk    bill@ardanlabs.com

**Comment by rjtch** [comment]
done! email sent.

**Comment by ardan-bkennedy** [comment]
Please write up your proposal or provide a PR with the changes and we can review it. We must make sure everything we do is in line with the design philosophies and guidelines. I have added content to the wiki, so we eventually need to make sure that is up to date.  Thanks!

**Comment by ardan-bkennedy** [comment]
Hi @rjtch, curious what the status was on this?

**Comment by rjtch** [comment]
Hello @ardan-bkennedy, i will make a pull request tomorrow.

**Comment by ardan-bkennedy** [comment]
Should I close this? @rjtch
