### ISSUE TITLE
Database pointer on handler level

### ISSUE THREAD

**Issue by yns01** [ardanlabs/service#102]
In the handler, you defined:
```
// Product represents the Product API method handler set.
type Product struct {
	db *sqlx.DB

	// ADD OTHER STATE LIKE THE LOGGER IF NEEDED.
}
```

What's the reasoning behind having a database access to be passed down the call stack? Also, why not having a dedicated layer, repository, to manage all the queries to the db?

**Comment by ardan-bkennedy** [comment]
Not every project needs that. We decided the business layer can have the intelligence to make the quieries they needed to make. Therefore, we pass the DB down into the business layer.

I have been on projects where the DB needed to be inside Ring 0 in terms of access.  In that project we needed to isolate all DB access to a single package. Event in that project, aquiring/releasing a connection can't be hidden from view.

**Comment by yns01** [comment]
> Not every project needs that. We decided the business layer can have the intelligence to make the quieries they needed to make. Therefore, we pass the DB down into the business layer.

Agreed. At first, I would assume that for services in production the business layer get big quite fast and the SQL queries in the middle can't possibly help. What's your experience there?

> I have been on projects where the DB needed to be inside Ring 0 in terms of access. In that project we needed to isolate all DB access to a single package. Event in that project, aquiring/releasing a connection can't be hidden from view.

Quite interesting, would you mind being more specific?

**Comment by ardan-bkennedy** [comment]
Send me an email   bill@ardanlabs.com
