### ISSUE TITLE
Initial 'make' fails b/c of missing private.pem

### ISSUE THREAD

**Issue by tullo** [ardanlabs/service#106]
Initial make fails with:
```
Step 10/27 : COPY private.pem private.pem
COPY failed: stat /var/lib/docker/tmp/docker-builder401590106/private.pem: no such file or directory
makefile:20: recipe for target 'sales-api' failed
```
Steps to reproduce:

1. `git clone --depth 1 https://github.com/ardanlabs/service.git`
1. `cd service/ && make`

**Comment by tullo** [comment]
What about a PR that adds `keys` as the first target for make all in the makefile?

**Comment by ardan-bkennedy** [comment]
I would like to better understand why this happened?

**Comment by tullo** [comment]
Exactly - the copy op fails for both docker image builds

**Comment by ardan-bkennedy** [comment]
Those files should be there. I’m wondering if the depth flag is affecting this?

**Comment by tullo** [comment]
**private.pem** is supposed to be a secret only known to the service and not to be shared or checked into VCS. Because of that `.gitignore` has an entry for `private.pem` and makes git ignore the file.
A "clean" checkout of the project is therefore missing the file and needs to be generated either by `make keys` or by adding the keys target to the default **make** `all: keys sales-api metrics` execution.

**Comment by ardan-bkennedy** [comment]
I don't know how that happened :(

I adding the pem file into the project. This is a starter kit so this is not a big deal.

**Comment by tullo** [comment]
It's good practice to not publish app secrets, passwords, TLS keys, etc and this project is all about good defaults.

I'd prefere to just generate/re-generate the pem file each time make all is run.

**Comment by ardan-bkennedy** [comment]
Absolutely correct. This is a starter kit and I don’t expect people to use this pem file. What’s important is the code builds after cloning.
