### ISSUE TITLE
Typo in Wiki for downloading the project

### ISSUE THREAD

**Issue by hoanhan101** [ardanlabs/service#110]
In [Downloading The Project](https://github.com/ardanlabs/service/wiki/Getting-Started#downloading-the-project), there is a typo for the command that is
```
$ GO111MODULE=off go get -d gitHub.com/ardanlabs/service
```
where should it be
```
$ GO111MODULE=off go get -d github.com/ardanlabs/service
```
instead!

**Comment by ardan-bkennedy** [comment]
Ugh!!  Thanks for letting me know.
