### ISSUE TITLE
Plan for supporting image manipulate

### ISSUE THREAD

**Issue by ghost** [ardanlabs/service#112]
Is there any plan to add the image server functionality to this package?

**Comment by ardan-bkennedy** [comment]
Can you please go into more detail?

**Comment by yuanlai** [comment]
It is common for server to save image uploading from client, and download from other client, so I think it is necessary to package this module into this project.

**Comment by ardan-bkennedy** [comment]
Sounds like another REST based call. It would have to fit into the garage sale metaphor, which I think it does. I can put this on my list to add.
