### ISSUE TITLE
Question: How to get the Search UI served?

### ISSUE THREAD

**Issue by tullo** [ardanlabs/service#113]
Hi Bill,

On the **_search_** branch I bootstrapped the services with `make up` and browsing the health endpoint works fine using http://0.0.0.0:5000/health

But what endpoint to hit for getting the `search.html` displayed? 

cmd/search/internal/handlers/routes.go shows that /static/ is stripped away from the path, so my guess is that http://0.0.0.0:5000/ should serve the UI but I currently get 404 for that.
Same for http://0.0.0.0:5000/css/main.css

```
SEARCH : 2020/02/20 17:28:00.746631 main.go:78: main : Started : Application Initializing version "c391787a78543663191e11e4f555e02c9f3e55a7"
SEARCH : 2020/02/20 17:28:00.746709 main.go:85: main : Config :
--web-api-host=0.0.0.0:5000
--web-debug-host=0.0.0.0:6000
--web-read-timeout=5s
--web-write-timeout=5s
--web-shutdown-timeout=5s
--zipkin-local-endpoint=0.0.0.0:5000
--zipkin-reporter-uri=http://zipkin:9411/api/v2/spans
--zipkin-service-name=search
--zipkin-probability=0.05
SEARCH : 2020/02/20 17:28:00.746726 main.go:102: main : Started : Initializing zipkin tracing support
SEARCH : 2020/02/20 17:28:00.746831 main.go:95: main : Debug Listening 0.0.0.0:6000
SEARCH : 2020/02/20 17:28:00.747080 main.go:150: main : API Listening 0.0.0.0:5000
SEARCH : 2020/02/20 17:31:59.074752 logger.go:34: d3d41c829cb0d6ea83aed5b97bc624e9 : (500) : GET /search -> 192.168.48.1:35650 (1.299281ms)
SEARCH : 2020/02/20 20:10:29.941274 logger.go:34: 7761c6e16a413deb561770312fb6877d : (200) : GET /health -> 192.168.48.1:48664 (33.701µs)
```

**Comment by ardan-bkennedy** [comment]
This was an experimental branch that was never completed. I couldn't tell you at all what state the propject is in. I should probably remove it.

**Comment by tullo** [comment]
Okay, good to know. I'm gonna look into it then - maybe I figure it out by myself, thanks.

**Comment by ardan-bkennedy** [comment]
I think you need `http://0.0.0.0:5000/search` but that assumes it is even working.

**Comment by tullo** [comment]
I had some time to give it another go. The current first draft is available here https://search-app-tullo.cloud.okteto.net/

Corresponding code: https://github.com/tullo/search
Maybe it's useful for you and that you are not having to many of the "code review stops right here" moments hven looking at code :sweat_smile:

**Comment by ardan-bkennedy** [comment]
Super cool. I love how you took want you wanted from service and made this work. Brilliant!  If I can find some time, I might take what I can from this for my search service, if that is ok.

**Comment by ardan-bkennedy** [comment]
How can I login?

**Comment by tullo** [comment]
user@example.com
gophers

**Comment by tullo** [comment]
> I might take what I can from this for my search service, if that is ok.

Sure, that's okay. You take what you can use.

**Comment by ardan-bkennedy** [comment]
I am doing UI work in this service.

https://github.com/dgraph-io/travel/tree/master/cmd/travel-ui
