### ISSUE TITLE
Proposal: unexport the `auth.Key`

### ISSUE THREAD

**Issue by oliverpool** [ardanlabs/service#115]
Currently `auth.Key` is only used to retrieve the `Claims` from the current `Context`:
```go
claims, ok := ctx.Value(auth.Key).(auth.Claims)
```

I t could be made unexported (`key`) by adding of two small helpers in the `auth` package:
```go
// ClaimsValue extract the Claims from the context
func ClaimsValuectx context.Context) (Claims, bool) {
	claims, ok := ctx.Value(key).(Claims)
	return claims, ok
}

// WithClaims add the Claims to the context
func WithClaims(ctx context.Context, claims Claims) context.Context {
	return context.WithValue(ctx, key, claims)
}

```

Which would be used like this:
```go
claims, ok := auth.ClaimsValue(ctx)
```

If you think this approach could make sense, I would be happy to make a PR

**Comment by ardan-bkennedy** [comment]
I am always concerned about helper functions. Adding code for the sake of doing it is not good. We want to reduce code and add to it. These particular helper function violate a guideline, IMO

Every encapsulation should define a new semantic where one is absolutely precise.

These functions are encapsulating one line of code. It is will clearer to the Go developer to just perform the Value call and type assertion. We all know what that code is and the cost of it. Abstracting that away doesn't make the code more readable. That's what an encapsulation needs to do.

**Comment by oliverpool** [comment]
ok, makes sense
