### ISSUE TITLE
Is it possible to create a WebSocket after authenticating in this project

### ISSUE THREAD

**Issue by yuanlai** [ardanlabs/service#119]
In this project, I find it already using http for all api method. If I want to create a WebSocket related method between client with server after `token` method,  is it possible to add it directly in `routes.go`?

**Comment by ardan-bkennedy** [comment]
Great question. I have not worked with web sockets before but yes, I would say the web socket handlers belong in the handlers package. Maybe add the route to `routes.go`. Maybe they can be organized in a different file in the package. Get something working first and then make a final decision for this.
