### ISSUE TITLE
Add staticcheck as a pre-requisite before "make test".

### ISSUE THREAD

**Issue by sreejeet** [ardanlabs/service#124]
On the wiki Getting Started page https://github.com/ardanlabs/service/wiki/Getting-Started
Could we add staticcheck as a pre-requisite along with docker. The tests fail if it is not installed or could not be found in the PATH.

https://staticcheck.io/docs

```staticcheck ./...
/bin/bash: staticcheck: command not found
makefile:50: recipe for target 'test' failed
make: *** [test] Error 127
```

**Comment by ardan-bkennedy** [comment]
Good Point and thanks. Because it is part of VS Code I didn't think about it.  Will Do!
