### ISSUE TITLE
Wrong signal in select?

### ISSUE THREAD

**Issue by dertseha** [ardanlabs/service#127]
In today's workshop at Gophercon Berlin, I followed the buildup of the service running on MS Windows.

There's an issue with the shutdown procedure, particularly with the select/case of the signal:
https://github.com/ardanlabs/service/blob/41310f4bf887db96d64aca10c56cb7c99606e47c/cmd/sales-api/main.go#L244
1. `syscall.SIGSTOP` is undefined
2. It is a different signal than is enabled in the `signal.Notify(...)` call earlier

Is this intentional? Or, more likely, a bug based on historical changes?

**Comment by ardan-bkennedy** [comment]
Great catch. That needs to be changed out for sure. Not sure exactly what it needs to be. Maybe that should be removed all together. 

Thanks,
— Bill

**Comment by ardan-bkennedy** [comment]
I ripped out that code so it's not going to be an issue anymore.
