### ISSUE TITLE
Avoid k8s manifest duplication based on platform

### ISSUE THREAD

**Issue by nstogner** [ardanlabs/service#128]
Kubernetes is intended to provide a consistent api no matter where it is running. It is considered an anti-pattern to maintain separate manifests depending on where k8s is running (`k8s/{gcp,kind}`). This is especially important if the different k8s platforms correspond to different app environments (kind == dev, gcp == prd) because you want to ensure you are maximizing parity as you promote your changes on its path to production.

Consider:
1. Using [kustomize](https://github.com/kubernetes-sigs/kustomize) to account for differences in manifests across environments while maintaining a common base manifest.
2. Using a tool like [skaffold](https://github.com/GoogleContainerTools/skaffold) to account for differences in local cluster development vs remote cluster deployment (avoid `kind load docker-image`, etc. in makefiles).

**Comment by ardan-bkennedy** [comment]
Awesome. More things to learn and teach!!  Let's figure out how we implement this. The project is designed to help with best practices.
