### ISSUE TITLE
Structure of business directory

### ISSUE THREAD

**Issue by farrukhny** [ardanlabs/service#135]
I have come to issue with current structure of business directory (business/data) when i need to query and return association between user and product (in my case user and role) with current structure if i want to return Products info (models) based on user ID and my func is in business/data/user pkg I have to create another struct of Products in user pkg and duplicate product struct then I can return result of query to my handler I can not import product struct from product pkg (import cycle not allowed).

**example.com/users/::USER_ID::/products** --- should return list of products associated with user.

and if I need to do same with product to return user association (if many to many)
 
**example.com/products/::PRODUCT_ID::/users** -- should return list of users associated with product.

So a options I can suggest:

Adding inside business/data/APP_NAME as in app folder and it make sense becasue this kind of monorepo structure

**example:**
business/data/sales-api/user
business/data/sales-api/product

and split models to own separate pkg so other pkg can import and avoid import cycle issue.

**example:**
business/data/sales-api/models
business/data/sales-api/models/user.go
business/data/sales-api/models/product.go

if you have better option please let me know :)

**Comment by ardan-bkennedy** [comment]
Nooo, none of this is good. Let's get on a call to discuss. Send me an email. bill@ardanlabs.com
