### ISSUE TITLE
Closing request body

### ISSUE THREAD

**Issue by JessBellon** [ardanlabs/service#137]
https://github.com/ardanlabs/service/blob/db61d927f5c6248895d9123f537b459261b1a904/foundation/web/request.go#L59

I might be missing something, but it seems like the `r.Body` is never getting closed?

**Comment by ardan-bkennedy** [comment]
This has always been confusing to me.

When you are making a request and then processing the body from the response, you need to Close the body. I don't believe when handling the request body you need to close it.

Here is the documentation from the http package. What do you think this is telling us?

    // Body is the request's body.
    //
    // For client requests, a nil body means the request has no
    // body, such as a GET request. The HTTP Client's Transport
    // is responsible for calling the Close method.
    //
    // For server requests, the Request Body is always non-nil
    // but will return EOF immediately when no body is present.
    // The Server will close the request body. The ServeHTTP
    // Handler does not need to.
    Body io.ReadCloser

**Comment by JessBellon** [comment]
I can't believe its written plain as day right there and I somehow missed it. 😬 
Thank you for the clarification!

**Comment by ardan-bkennedy** [comment]
This is confusing and not obvious. Your question made me look it up again.
