### ISSUE TITLE
Error building sales-api image

### ISSUE THREAD

**Issue by rmsj** [ardanlabs/service#139]
❯ make sales-api
docker build \
                -f zarf/docker/dockerfile.sales-api \
                -t sales-api-amd64:1.0 \
                --build-arg VCS_REF=`git rev-parse HEAD` \
                --build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \

"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
make: *** [sales-api] Error 1

environment:

❯ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by rmsj** [comment]
It worked with this small change:

`docker build \
		-f ./zarf/docker/dockerfile.sales-api . \
		-t sales-api-amd64:1.0 \
		--build-arg VCS_REF=`git rev-parse HEAD` \
		--build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \`

Note the . to at the end of the path - (context) and at the start.

**Comment by ardan-bkennedy** [comment]
My make file already has the `.`

```
sales:
	docker build \
		-f zarf/docker/dockerfile.sales-api \
		-t sales-api-amd64:1.0 \
		--build-arg VCS_REF=`git rev-parse HEAD` \
		--build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
		.

metrics:
	docker build \
		-f zarf/docker/dockerfile.metrics \
		-t metrics-amd64:1.0 \
		--build-arg VCS_REF=`git rev-parse HEAD` \
		--build-arg BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”` \
		.
```

And these commands are working?

**Comment by ardan-bkennedy** [comment]
Looks like I changed sales-api to sales at some point :(. I will look at the wiki.

**Comment by ardan-bkennedy** [comment]
I am not having a problem building this with the current makefile and no changes. Not sure what to do here?
