### ISSUE TITLE
Consider adding an IDL (OpenAPI / Swagger)

### ISSUE THREAD

**Issue by nstogner** [ardanlabs/service#14]
Having some sort of interface definition is extremely useful as it provides a clear API contract for clients. For a REST API this should probably follow the OpenAPI spec (https://en.wikipedia.org/wiki/OpenAPI_Specification).

Usually there is some sort of automated link between the server's codebase and the IDL. This can be one of two directions: code generated from IDL or IDL generated from code. A few thoughts on each direction:
1. IDL --> Code: OpenAPI/swagger docs are a pain to write IMO (I much prefer gRPC's protobuf IDL as it is very clean IMO). This route may limit package-structure choices.
2. Code --> IDL: Last I checked the go swagger tool generates the JSON IDL off of code comments. It was brittle from my experience b/c it elevated comments to a level where they had side-effects that could influence production systems.

These items should be tackled sooner rather than later b/c if we choose to link the codebase and IDL in some automated way, it has big implications on the project's code structure.

**Comment by ardan-bkennedy** [comment]
My initial reaction is one of fear when I see the words "code generation". LOL

The idea of the IDL being generated from the code is interesting. Could you show more concrete examples of this?

**Comment by wyattjoh** [comment]
I know that [goa](https://goa.design/design/swagger/) will generate the swagger documentation files easily, but without lots of custom code to handle it, `service` can't easily generate their swagger files as far as I know.

**Comment by ardan-bkennedy** [comment]
I don't want to bring in goa or anything like it. The idea is to minimize dependencies and keep this code base minimized and readable. That is a first priority.
