### ISSUE TITLE
Add explanation of app/sidecar/metrics to wiki?

### ISSUE THREAD

**Issue by jakelowen** [ardanlabs/service#145]
Just finished the course (twice) and have applied the basic structure to the start of solving my own business problem. Excellent stuff.

The repo contains a sidecar app at `app/sidecar/metrics` and I see it referenced in the various compose/k8s configs, but the video content or wiki never addresses it at all.  Can you add a small section to the wiki or comments in the code itself describing the purpose of this sidecar and its role in the larger server stack?

I can expvarmon just fine without it thanks to the expvar support in the core project. I just don't understand yet why I'd want to pull this sidecar into my deployment?

**Comment by ardan-bkennedy** [comment]
Great point and I will add it to the wiki. I wanted to teach POD based microservices with the sidecar and then realized I would be repeating myself a bit. I should have mentioned something in the video. Your solution is a great idea.

**Comment by ardan-bkennedy** [comment]
Please let me know if this helps.

https://github.com/ardanlabs/service/wiki#services
