### ISSUE TITLE
Question on the json tag on Error

### ISSUE THREAD

**Issue by haibin** [ardanlabs/service#147]
One question: Do you think it's a bit not consistent that `Error` does not have json tag but its `Fields` has json tag. Do you think we can remove `ErrorResponse` and add json tag to `Error` to make it consistent? It's minor but I'd like to know your idea on this.

https://github.com/ardanlabs/service/blob/0c632a8aa61bef003a2b7a7ca8f59d09b49b68df/foundation/web/errors.go#L7-L25

**Comment by ardan-bkennedy** [comment]
There are a few reasons to keep this separated.

1. These values provide a different set of concerns. Remember, make things easy to understand, not easy to do. One is for reporting errors through the application (Error). One is for reporting errors over the wire back to the client (ErrorResponse).

2. I want to control the string that is returned and I want to omit Fields when there are no field issues. This separation makes that less bug prone.
