### ISSUE TITLE
Use sql.Named instead of positional arguments

### ISSUE THREAD

**Issue by tebeka** [ardanlabs/service#150]
The SQL queries in `user.go` and `product.go` use positional argument to the query. I find it more readable and less error prone to use named arguments with [sql.Named](https://golang.org/pkg/database/sql/#Named):

```
	INSERT INTO users
		(user_id, name, email, password_hash, roles, date_created, date_updated)
	VALUES
		($1, $2, $3, $4, $5, $6, $7)`
```

Becomes
```
	INSERT INTO users
		(user_id, name, email, password_hash, roles, date_created, date_updated)
	VALUES
		(@user_id, @name, @email, @password_hash, @roles, @date_created, @date_updated)`
```

**Comment by ardan-bkennedy** [comment]
Funny, I inherited this code and figured it was a sqlx thing. I will look into this for sure because I think it can potentially simply the logging. Thanks!

**Comment by ardan-bkennedy** [comment]
I just pushed a new release that uses named arguments. Built some nice support in the database package for query calls.  Thanks for the tip.
