### ISSUE TITLE
GCP Wiki Section: Makefile has been moved

### ISSUE THREAD

**Issue by ciprian-cimpan** [ardanlabs/service#152]
The GCP section in the [wiki](https://github.com/ardanlabs/service/wiki/running-gcp#makefile) mentions a `Makefile` that is no longer present inside `/k8s/gcp`.

The rules related to GCP have been moved in the main `makefile`, which is located in the project's root.

**Comment by ardan-bkennedy** [comment]
Great catch!!  I will fix that today.

**Comment by ardan-bkennedy** [comment]
I updated the wiki page. I have not run this in GCP/GKE for a while. This might be broken. If you try this and find things that need to be changed, please let me know.
