### ISSUE TITLE
CORS & SetMaxOpenConns

### ISSUE THREAD

**Issue by jonleopard** [ardanlabs/service#157]
Hello!

I'm going over this course again and noticed that CORS wasn't really addressed in any of the lectures. Do you think it might be valuable to add a small section for that in the course? Also, `SetMaxOpenConns` is not being defined in the config.  I read this very interesting [article](https://sudhir.io/understanding-connections-pools/) that suggests it being set. Here's an excerpt:

> Because Go is automatically geared for tens of thousands of simultaneous requests even on very small servers, pairing it with a process-based database like PosgreSQL is often like driving a race-car into a brick wall. If each goroutine is using the standard library SQL package, it will create as many connections as there are goroutines—because the default pool size is unlimited. The first thing you'd want to do on any Go application using a SQL DB is to configure the connection limits using `SetMaxOpenConns` and the associated options. Go uses an internal pool on the sql package, so each query you run will checkout a connection from the pool, use it and release it back immediately. This means that if you want to execute a transaction, you must use the special methods that give you an object that wraps the connection you started the transaction on, which is the only way you can later commit or rollback that transaction. This is also every important when using other functions that are connection specific, like prepared statements or advisory locks.

Let me know what you think!

Cheers :)

**Comment by ardan-bkennedy** [comment]
Hi Jon, I will leave this issue here and look at this ASAP. I have a few other pending things to get to.

I've implemented CORS before but it was a while ago. I would like to consult a friend of mine on this. Just need to think of a proper use case.

I'll read the article as well on the open conns.

Thanks!!

**Comment by ardan-bkennedy** [comment]
I think this should be applied at the route level unless every single route needed these headers.

I like the solution.

Create a PR adding this middle to the mid package and the new config setting with that default.

I won't apply this to any route at this time.

Make sure you add yourself to the CONTRIBUTORS files as well please.

**Comment by jonleopard** [comment]
@ciprian-cimpan Thanks for the info! I'll go ahead and wait for the new PR to be merged and pull it in whenever its finished.

**Comment by ciprian-cimpan** [comment]
@jonleopard you're welcome! 👍🏼 
I just submitted the [PR](https://github.com/ardanlabs/service/pull/160)

**Comment by ardan-bkennedy** [comment]
@jonleopard I added the Idle/Open connection settings.
