### ISSUE TITLE
Error when trying to create a new user

### ISSUE THREAD

**Issue by jonleopard** [ardanlabs/service#159]
I’m trying to connect a NextJS (react) client to the API. Just to test things out, I am using the same insecure keys and what not.

So far I have:

1. Generated a bearer token for the NextJS client so that it can communicate with the go backend, and stored it in an environment variable for future requests.

` curl --user "admin@example.com:gophers" http://localhost:3000/v1/users/token/54bb2165-71e1-41a6-af3e-7da4a0e1e2c1
`

2. Tried mocking a test query to create a new user, and I get the following error back:

```
{
  "error": "json: cannot unmarshal string into Go struct field NewUser.roles of type []string"
}
```

![Screenshot 2021-03-24 at 18 43 33](https://user-images.githubusercontent.com/2111234/112358857-fff0f600-8cd0-11eb-8259-464704a14a9a.png)

`Roles` is a required field at signup, is there something I'm doing wrong here?

**Comment by ardan-bkennedy** [comment]
The roles need to be a collection.

“roles”: [“USER”]

**Comment by jonleopard** [comment]
Worked, thank you!
