### ISSUE TITLE
Consider using a struct for config

### ISSUE THREAD

**Issue by nstogner** [ardanlabs/service#16]
I like the idea of having a `type config struct` in the `main` package. It provides a simple declarative way of showing all inputs that can effective application behavior. You can then populate it from the env (i.e. https://github.com/kelseyhightower/envconfig) or somewhere else on startup.

**Comment by nstogner** [comment]
This also makes it easy to inspect configuration options/defaults. For example: https://godoc.org/github.com/kelseyhightower/envconfig#Usage

**Comment by ardan-bkennedy** [comment]
I have a philosophy problem with this. I think it hides information. I don't want to pass all the configuration around, especially when it is not all needed in all places. I think what we are doing is solving the problem you descibed.

**Comment by nstogner** [comment]
I wouldn't advocate for passing the entire struct to things created from `main()`, just the variables that they need
```
func main() {
    var cfg struct{
        ABC string
        XYZ int
    }

    // TODO: Process config from source (i.e. env)

    something := NewSomething(cfg.ABC, cfg.XYZ)
}
```

**Comment by ardan-bkennedy** [comment]
So is this really enhancing readability of the code or just adding to it?

**Comment by ardan-bkennedy** [comment]
Nick, create a PR for this and let's look at it. I think it is just adding an extra local type that is not necessary but maybe it will enhance readability.

**Comment by ardan-bkennedy** [comment]
Here is the pull request for this change.

https://github.com/ardanlabs/service/pull/22

**Comment by ardan-bkennedy** [comment]
This has been merged.
