### ISSUE TITLE
How to use another router?

### ISSUE THREAD

**Issue by jonleopard** [ardanlabs/service#162]
Hello! No issues with `httptreemux`, nor am I suggesting it be replaced. I'm just more familiar with [Chi](https://github.com/go-chi/chi) and was curious if it was even possible to use it instead? In lecture video 5.6, its explained how `httptreemux` returns a map in the `Params` function. I'm not certain that Chi behaves the same way under the hood. At first glace, this is how the two differ when it comes to defining parameters:

httptreemux: `/api/v1/post/:postid`
chi: `/api/v1/post/{postid}`

`httptreemux`  returns a map of string, `chi` doesn't have a  function that behaves like that. I think the closest would be [`chi.URLParamFromCtx`](https://pkg.go.dev/github.com/go-chi/chi#URLParamFromCtx), but that doesn't seem right either.  If anyone here is familiar with `Chi` and has used in it their own branch of the project, do you have any suggestions?

#### request.go - old

```
// Params returns the web call parameters from the request.
func Params(r *http.Request) map[string]string {
	return httptreemux.ContextParams(r.Context())
}
```

#### request.go - new

```
func Params(ctx context.Context, key string) string {
	return chi.URLParamFromCtx(ctx, key)
}
```

No issues in the `app.go` file:

app. go
```
type App struct {
	mux      *chi.Mux
	otmux    http.Handler
	shutdown chan os.Signal
	mw       []Middleware
}



func NewApp(shutdown chan os.Signal, mw ...Middleware) *App {
	mux := chi.NewRouter()

	return &App{
		mux:      mux,
		otmux:    otelhttp.NewHandler(mux, "request"),
		shutdown: shutdown,
		mw:       mw,
	}
}


func (a *App) handle(debug bool, method string, path string, handler Handler, mw ...Middleware) {
	if debug {
		if _, exists := registered[method+path]; exists {
			return
		}
		registered[method+path] = true
	}

	handler = wrapMiddleware(mw, handler)

	handler = wrapMiddleware(a.mw, handler)

	h := func(w http.ResponseWriter, r *http.Request) {

		ctx := r.Context()
		ctx, span := trace.SpanFromContext(ctx).Tracer().Start(ctx, r.URL.Path)
		defer span.End()

		v := Values{
			TraceID: span.SpanContext().TraceID().String(),
			Now:     time.Now(),
		}
		ctx = context.WithValue(ctx, KeyValues, &v)

		if err := handler(ctx, w, r); err != nil {
			a.SignalShutdown()
			return
		}
	}

	if debug {
		f := func(w http.ResponseWriter, r *http.Request) {
			switch {
			case r.Method == method:
				h(w, r)
			default:
				w.WriteHeader(http.StatusNotFound)
			}
		}
		http.DefaultServeMux.HandleFunc("/debug"+path, f)
		return
	}
	a.mux.MethodFunc(method, path, h)
}
```

**Comment by ardan-bkennedy** [comment]
The whole point of this code is that it’s NOT a framework so you can change out anything you want.

I think you want this API call instead
```
  userID := chi.URLParam(r, "userID")
```
So something like this

```
func Params(r *http.Request, key string) string {
	return chi.URLParam(r, key)
}
```

This is as close to what I have.

```
func Params(r *http.Request) chi.RouteParams {
	rctx := RouteContext(r.Context())
	return rctx.URLParams
}
```

**Comment by jonleopard** [comment]
Thanks for putting me on the the right track! I used your snippet, and there's an issue in `/sales-api/handlers/user.go` where we call `web.Params`:

line 33: `pageNumber, err := strconv.Atoi(params["page"])`

```
[compiler NonIndexableOperand] [E] invalid operation: cannot index params (variable of type chi.RouteParams)
```

I'm still learning my Go chops, but I think this is because before we were returning `map[string]string` for `Params`, and now `Params` is returning `chi.RouteParams`.  So I need to change the way I wrap `["page"]` in `user.go`?

**Comment by ardan-bkennedy** [comment]
That code needs to change. You will need to use the methods for the RouteParams. The return type is different.

**Comment by ardan-bkennedy** [comment]
Looking at this more closely, you need this instead
`chi.URLParam(r, key)`

Change web.Params to be web.Param
```
func Param(r *http.Request, key string) string {
	return chi.URLParam(r, key)
}
```

Then this

```
pageNumber, err := strconv.Atoi(params["page"])
```

becomes

```
pageNumber, err := strconv.Atoi(web.Param(r, "page"))
```

**Comment by jonleopard** [comment]
Works like a charm! Thank you for taking the time to look at this for me!

Cheers
