### ISSUE TITLE
Account creation question via client

### ISSUE THREAD

**Issue by jonleopard** [ardanlabs/service#166]
I have sort of an architectural question here. This repo is my reference for starting any REST project (I took the course and learned so much from it).

I’m trying to set up a [NextJS](https://nextjs.org/) client that can make requests to the service backend. To get started, there’s a signup page. Since this is all just practice, the user model is the same and my fields on the signup page match the [NewUser](https://github.com/ardanlabs/service/blob/09b5b383768b16f7bc23f1d9cfa4b17a5d9458a2/business/data/user/models.go#L21) model. 

The [docs](https://github.com/ardanlabs/service/wiki/running-kind#authenticated-requests) indicate that before any requests can be made, an auth token must be acquired. This is what trips me up, the NextJS client can’t make any API requests without a token, and to get a token, a user must already exist in the DB.

There's a handy [useradd](https://github.com/ardanlabs/service/blob/master/app/sales-admin/commands/useradd.go) utility that can create a user from the CLI, but the client also needs the ability to let users create an account. Do I need to implement an endpoint that doesn't require a token to make an account? Once the user is logged in, the jwt info would be stored in something like `localstorage` so that any subsequent requests can be authorized.

Any input would be very helpful!

Thanks

**Comment by ardan-bkennedy** [comment]
You can make the registration page token free and have that create a new user and return a token. You can seed a user for the registration page that has a token that is only allowed to use the registration page.

You don't need to store the JWT for the user. That is there responsibility. I would just recreate the token if they needed a new one. All you are doing to validating the token was signed by you and respecting the claims.

**Comment by jonleopard** [comment]
Thanks for the explanation! 

> You can seed a user for the registration page that has a token that is only allowed to use the registration page.

I’m curious why this is necessary? Are we just making sure that the client (NextJS app) is ‘authenticated’ to create accounts in the system? I would love to study/understand this more. Do you know of any existing frameworks or OSS projects that behave similarly? I've seen some go jwt examples, but they don't do any authentication like this (you just signup from the app, request hits to the api, and then a jwt token gets returned in the payload) which leads me to think those examples aren't production ready.

**Comment by jonleopard** [comment]
Understood. I'm gonna think about how I want to approach this. Thanks so much for your input! Closing now.
