### ISSUE TITLE
Error wrapping

### ISSUE THREAD

**Issue by ciprian-cimpan** [ardanlabs/service#167]
All other errors in this layer seem to be wrapped, except this one:
https://github.com/ardanlabs/service/blob/09b5b383768b16f7bc23f1d9cfa4b17a5d9458a2/app/sales-api/handlers/product.go#L44

Is it done for a specific reason or is it a typo?

**Comment by ardan-bkennedy** [comment]
I believe that is on purpose because the potential error is handled in a specific way. That being said, we could wrap it and see if the tests still pass.

**Comment by ardan-bkennedy** [comment]
I want to leave this open to validate the situation.

**Comment by ardan-bkennedy** [comment]
You were right, that error should have been wrapped. Fixed!
