### ISSUE TITLE
Shutdown Err

### ISSUE THREAD

**Issue by typecampo** [ardanlabs/service#168]
https://github.com/ardanlabs/service/blob/d69171c7be1e88996326b44c41bdc66620c163c9/foundation/web/response.go#L21

If you have a shutdown error caused by a missing context, when this returns, the response never gets sent?

**Comment by ardan-bkennedy** [comment]
If this code has to run, we have a MAJOR integrity issue. The most important thing is shutting down. Honestly, this would probably have been caught before getting to this function.

That being said, at this point that client request would be abandoned. So I think this is a good catch.

Would you like to provide a PR or have me fix it?

**Comment by typecampo** [comment]
You fix it please. 

I had some thoughts around having a Response with context and one without context for this particular situation. 

I understand the integrity issue but I feel if the program has the ability to send a response before shutting down, it should do so.

**Comment by ardan-bkennedy** [comment]
I agree. Will do it soon.

**Comment by ardan-bkennedy** [comment]
Done
