### ISSUE TITLE
Update cfg to add flags to the command line

### ISSUE THREAD

**Issue by ardan-bkennedy** [ardanlabs/service#17]
Peter Bourgon in his talk at Iceland made a point that services should have flags for all possible configuration options. This helps operation and with documentation. The cfg package should add the support for this since it is a single place for configuration knowledge.

**Comment by ardan-bkennedy** [comment]
Going to write a package to add support for updating the config struct based on tags. The final idea is to add this to envconfig

**Comment by nstogner** [comment]
Is the plan to allow flags to override env vars? i.e. env: `DB_USER` corresponds to flag: `--db-user`?

**Comment by ardan-bkennedy** [comment]
Here is the [PR](https://github.com/ardanlabs/service/pull/25)

**Comment by nstogner** [comment]
PR for `internal/platform/flag` merged.
