### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by farrukhny** [ardanlabs/service#170]
I think it will be better to handle error logs in handlers before returning error and let Error middleware only take care of sending response to end user. We are already passing logger to data func. This give us more flexibility to log specific details about the error and not expose to end user. Also maybe to reduce amount of logs in info levale we should changed data func log.info to log.debug.

```go
func (pg productGroup) queryByID(ctx context.Context, w http.ResponseWriter, r *http.Request) error {	
   ctx, span := trace.SpanFromContext(ctx).Tracer().Start(ctx, "handlers.productGroup.queryByID")	
   defer span.End()
	
  v, ok := ctx.Value(web.KeyValues).(*web.Values)	if !ok {		
     return web.NewShutdownError("web value missing from context")	
  }

  id := web.Param(r, "id")	
  prod, err := pg.store.QueryByID(ctx, v.TraceID, id)
  if err != nil {		
      switch errors.Cause(err) {	
        case database.ErrNotFound:
			// we can skip this
                return validate.NewRequestError(err, http.StatusNotFound)	
        case database.ErrInvalidID:
		pg.log.Errorw(err.Error(), "product", id, "method", "queryByID")	
                 return validate.NewRequestError(err, http.StatusBadRequest)	
        default:
		pg.log.Errorw(err.Error(), "product", id, "method", "queryByID")	
                return errors.Wrapf(err, "ID: %s", id)		
      }	
 }
	
return web.Respond(ctx, w, prod, http.StatusOK)}
```

change data func log:

```go 
s.log.Debugw("product.Create", "traceid", traceID, "query", database.Log(q, prd))
```

**Comment by ardan-bkennedy** [comment]
I think the logging/error middleware should provide a trace log for every request and error. That shouldn't be left up to the handler developer to remember to do. I want consistency with that. Handling an error means logging the error.

But it is totally fair for you to add extra logging where you think it's necessary.  The less you log, the more signal you will have. I just want you to be absolutely sure that information is necessary and useless. I don't see how you example provides more quality information beyond what the error handler is doing. If anything it's a duplication of code.

I don't believe in log levels. The zap logger enforces it on me, so I am using info and error. In production I would want to see all of it.
