### ISSUE TITLE
Question: Reusable Code

### ISSUE THREAD

**Issue by typecampo** [ardanlabs/service#175]
If the app directory were to contain other closely related apps, would it make more since to have an app package for the general layout of the run function? Even if you were to put each app in its own repository, you would still have to copy over the general structure of the run function.
```
app/
    app1/
        main.go
    app2/
        main.go
...
```
Take this line for example, if you wanted to change the string, you would have to change it in all the other apps main.go as well.
https://github.com/ardanlabs/service/blob/fa7293d9d8974bc37306a739ca55c9222ff1c5d3/app/sales-api/main.go#L124

**Comment by ardan-bkennedy** [comment]
I understand where you are going. The DRY rule. But sometimes it’s better to copy and paste code. When it comes to application startup, I don’t think you want to apply DRY here.

**Comment by typecampo** [comment]
Does it make since to have a common package that holds formats, Err, and strings common to the run function? Im just thinking if I have many apps and I want to change one thing, I have to do it in every single app. I suppose though this is where you we prefer readability over easier to do. Feel free to close.

**Comment by ardan-bkennedy** [comment]
I could say the same for making a change that could break all the other services. Or a change that only one service needs. 

As an example, my sidecar doesn’t need everything the main service needs. Sometimes it’s better to isolate things to minimize the surface area of a change. 

This is a starter-kit. Make your copy and try out your ideas. See how it goes.
