### ISSUE TITLE
Question about how to structure thirdparty calls

### ISSUE THREAD

**Issue by rockey5520** [ardanlabs/service#176]
Hello :)

I got rather a basic question, one use case I could not able to see if explored in this example and wondering how others approach towards this below kind of situations

Imagine a web service has lots of 3rd party API's it needs to interact at various points (for example, in order to fetch an optimal vacation plan, an execution might need to interact with google calendar to find free days, a weather API to find the right destination place to fly, Skyscanner to check for correct flights, and so on ) how to structure these several third-party calls into the app structure that fits well?

another example: If the application database is not a traditional database rather it's something you interact via API, such as Aurora data API how to configure the database code during application start-up?
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html

Apologies if my question doesn't make sense, happy to rephrase if needed so.

Thanks in advance
Rakesh

**Comment by ardan-bkennedy** [comment]
I do this in the travel repo (https://github.com/dgraph-io/travel). You will see under business a feeds layer. There I have packages that just return data. They don't hit the database as all. The data layer has packages that hit the database.

Whatever package you build to talk wuth Aurora needs a factory function that takes a config. Then in main.go you can extend the config struct for the config parameters you need.

**Comment by christian-korneck** [comment]
just as a thought, I would find an example for a simple call to an external api a very useful addition to the service repo/course. It’s such common requirement in real world projects.

**Comment by ardan-bkennedy** [comment]
I get it. So please look at the travel repo and you will find what you are looking for.

**Comment by rockey5520** [comment]
Thanks @ardan-bkennedy I will take a look at https://github.com/dgraph-io/travel :)
