### ISSUE TITLE
Question/discussion about how basic authentication is done

### ISSUE THREAD

**Issue by nahojer** [ardanlabs/service#177]
Hi! First I wanna say that I've been following this project for quite some time now and find it interesting how it has evolved. I am very grateful that this project exists as I learn a lot.

To the question. I read an [article](https://www.alexedwards.net/blog/basic-authentication-in-go) about how to do basic authentication. In order to prevent timing attacks, they suggested one should use Go's `subtle.ConstantTimeCompare()` function to check if the provided username and password _hashes_ equal the expected username and password _hashes_. They also pointed out that it's important to evaluate both the username (in this project, email) and password _before_ checking the return values of `subtle.ConstantTimeCompare()` to avoid leaking information. Furthermore, they also set ```w.Header().Set("WWW-Authenticate", `Basic realm="restricted", charset="UTF-8"`)``` and not just the status code to 401 in order to to inform the client that we expect them to use basic authentication.

Is this something that this project is interested in implementing, or is it overkill? Would love to hear your viewpoint on this.

**Comment by ardan-bkennedy** [comment]
I talk to some of this stuff when I am teaching. JWT and this implementation is just a starting point and most projects do need to build something on top of it.

The beautiful part of this project is that you can rip it apart and put it back together again. So please add these features if they are important to your project. I will add this post to the reading document.
