### ISSUE TITLE
Logging typo

### ISSUE THREAD

**Issue by ciprian-cimpan** [ardanlabs/service#179]
https://github.com/ardanlabs/service/blob/5e5d367c30176d890e16078aa9d66a1a28191bd5/business/sys/database/database.go#L139-L142

Should be `log.Infow("database.NamedQueryStruct", ...` instead of `log.Infow("database.NamedQuerySlice", ...`

**Comment by ardan-bkennedy** [comment]
Yup. Thanks for catching that. I will check master.

**Comment by ardan-bkennedy** [comment]
Fixed
