### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by ardan-bkennedy** [ardanlabs/service#18]
We need to add a minimal but complete layer for authentication and authorization.

**Comment by nstogner** [comment]
First thoughts are to use JWT and add https://github.com/dgrijalva/jwt-go as a dependency to the middleware package. Tokens can be generated elsewhere.

**Comment by ardan-bkennedy** [comment]
We should teach to how to maintain secrets in code as well.

**Comment by nstogner** [comment]
I think we should use asymmetric encryption (RSA). This way the service that consumes/validates tokens only needs the RSA public key which mitigates secret exposure risk. A separate service would be used for token generation. In this service we would demonstrate the handling of secrets (RSA private key) and possibly the storage of user passwords. This token-generation service would most likely manage the CRUD for user resources.

For reference:
https://auth0.com/blog/json-web-token-signing-algorithms-overview/

**Comment by nstogner** [comment]
@ardan-bkennedy Do we want to support multi-tenancy? My vote is no for simplicity's sake.

**Comment by jcbwlkr** [comment]
I vote no on multi tenancy

**Comment by ardan-bkennedy** [comment]
I vote no as well.

**Comment by nstogner** [comment]
Closed, will open Authorization issue separately.
