### ISSUE TITLE
[typo] Wrong type for fmt.Errorf()

### ISSUE THREAD

**Issue by ciprian-cimpan** [ardanlabs/service#181]
https://github.com/ardanlabs/service/blob/a534150d4ae291ba54cd1e759cf48042066c6b60/business/core/report/report.go#L31-L39

Both error lines should return a string for `UserID [%s]`, with the first one being `UserID` _(as the `user` will be empty in case of an error)_. The second one can also be `user.ID`.

**Comment by ardan-bkennedy** [comment]
Ugh. Thanks!
