### ISSUE TITLE
.gitignore update

### ISSUE THREAD

**Issue by ciprian-cimpan** [ardanlabs/service#182]
https://github.com/ardanlabs/service/blob/e0e284ca8200660f51030d8d10529893a213a20c/.gitignore#L1-L4

.gitignore should also be updated to reflect the new `app layer` changes:

```
# Binaries
app/tooling/sales-admin/sales-admin
app/services/sales-api/sales-api
app/services/metrics/metrics
```

I never built a binary for this project directly, nor do I see a `makefile` command to build them that way - so it's probably safe either way, but just in case someone runs a `go build` in the folder...

**Comment by ardan-bkennedy** [comment]
I'm too busy and moving too fast. I can't tell you how much I appreciate the help. I do accept PRs.  Hahaha

I will make this change now.

**Comment by ciprian-cimpan** [comment]
Oh, sorry about that. 
Ok, I will create PRs from now on if I see anything worth mentioning. 👍
