### ISSUE TITLE
Proposal to move authorization logic from `data/store` to `core`.

### ISSUE THREAD

**Issue by ciprian-cimpan** [ardanlabs/service#186]
Hi Bill!

I have a suggestion regarding the recently added `core` package in the `business` layer.

I think it's great to have an extra layer between `handlers` and the `data/store`.
Before, I would find myself adding "business-like" logic inside the handlers.
So having the new `core` cleans up things quite a bit for me.

However, the new `core` package helped me with one more thing: cleaning up the layer below (`data/store`) from similar "business-like" logic.

For the starter service, the authorization is pretty simple, often involving a `RoleAdmin` check and/or `entity_author vs claims.Subject` check.
In my own work, authorization has usually been more complex, often involving checks across different entities and also calls to third-party services, before a record is finally "committed" to the database.

In my case moving such authorization logic from `data/store` to `core` made more sense, so I wanted to ask you if you would consider such a change for the starter service too.

In my view it feels cleaner to keep the `data/store` as "dumb" as possible, since the scope of most requests ends at this point, with a modified repository record. Such logic would then be moved in the new `Pre-Business Operations` spots of their `core` counterparts.

As a further argument, consider the `data/store/Update()` method.
The first two `validate.Checks` are clearly linked with what happens next.
But the authorization happening at lines ~70-78 could involve checks that are very unrelated to the scope/responsibility of this method (i.e. checks if you're also an admin in a 3rd party service).

What do you think, does it make sense to move that (and other auth-related checks) in `core` instead?

Thanks & have an awesome day,
Ciprian

https://github.com/ardanlabs/service/blob/da8e2946b4dded372e2f56ef8c6d6bc91a737ac1/business/data/store/product/product.go#L62-L78

**Comment by ardan-bkennedy** [comment]
Yes you can move that as long as it doesn’t create data integrity issues if someone uses the data layer directly. 

At this point I’m afraid bypassing core is an option. If in your project you can guarantee it won’t happen go for it. 

It’s complicated at times to decide what is needed in the data layer and what is your business logic. In my head data integrity must be maintained.

**Comment by ciprian-cimpan** [comment]
Ok, got it! 
I never thought about the scenario when the data layer is being accessed directly, but that's indeed a valid case of concern. 

It makes sense to strive for data integrity, although in my case I'll choose to leverage the new `core` layer. 
I ended up dumping way too much logic inside `data/store`, so it didn't feel like a database-related package anymore.  

I'll keep the integrity concerns in mind, thanks for pointing that out!

**Comment by ardan-bkennedy** [comment]
Check out the core branch. My team has been debating this for a good week. We decided to prototype it. I think it works well but in the end, no one can call into the data layer from the app layer. Core is the API.

**Comment by ciprian-cimpan** [comment]
## [+] Core as API
Yes, I really like it! 

After adding the core layer into my fork I noticed that most of the business logic sitting above it _(handlers)_ and below _(data)_ found its home in the new layer, somehow "naturally". 

So I couldn't agree more that `Core` should be center of the API, with data _(and maybe other future layers)_ feeding into it. 
I'm the biggest fan of this change, lol 😄


## [+] Data Integrity
Your data integrity comment made me realize the importance of it, and that it should be indeed regarded as paramount. 

It's not applicable in my own case, but in large teams, new hires working on this project might not "read the instructions" and could access the data layer from unauthorized places.

I was thinking about adding a new context value (a bool like `isAuthorized`) and use it as a further check in the `data` layer.
This way, it acts like a switch - if you call it from where authorization checks weren't performed, you must at least turn it on _(manually put that bool on the context)_. 

So having it there guarantees that either an authorization check has been done, or the developer manually toggled it on. 
In the latter case, we'll assume it was done with purpose, thoroughly knowing the risks involved, haha.

I know adding new values on the context is generally frown upon, but I think it makes sense in this specific case, as I think it's very related to this request _(if it's authorized or not)_.

What do you think, could this work?


## [+] Authentication Errors
I like the addition of all types of errors (not just jwt-related) in `auth` - I have them there too. 


## [-] Prefixed entities
I'm not a big fan of the `db` prefix, though. 
I'd rather have it as before or similar to `[business] / [data] / [db] / [entity]`. 

`db` could also be `postgres`, to make it clearer in case multiple database systems will eventually feed into the `core`.

In such a scenario, where multiple services like `postgres`, `mysql`, `firebase`, etc feed data to the `core`, having entities with prefixes could become inconvenient. The file names could become too long and less readable.

**Comment by ardan-bkennedy** [comment]
Two things. Don’t worry about any app layer code accessing the data layer. Catch that in review. 

I’m experimenting with the db prefix to have a unique package name. I see the need for an alias as a smell. 

db is generic enough. If you run into scenarios as you mention, then I think you can try different options. Don’t do things for a future that doesn’t exist yet. Focus on what you have. 

My team will review this on Monday. Let’s see what sticks.

**Comment by ciprian-cimpan** [comment]
Sounds great - thanks for looking into this!

**Comment by ardan-bkennedy** [comment]
These changes are final for now. I think they are interesting and good.

**Comment by ciprian-cimpan** [comment]
Really nice! 
I agree & also think the new updates fit the project quite well.

Since now `Core` acts as the API, and you mentioned previously that aliases are kind of a smell, what do you think about dropping all aliases to `entityCore`? 

Like the ones in handlers:
```
productCore "github.com/ardanlabs/service/business/core/product"
userCore "github.com/ardanlabs/service/business/core/user"
```

As a personal preference, I will keep the `data/store` layer around, at least for a while longer. 
I understand it makes more sense to merge it with each entity _(like now, in the core layer)_, but I currently find some use in preserving the old structure, with business & data logic clearly separated from each other in non-related layers.

**Comment by ardan-bkennedy** [comment]
No, those should be refatored. I missed it.

Yea, keep experimenting and see where it goes. We have a larger project that moved us in this direction.
