### ISSUE TITLE
Graceful terminations within Kubernetes

### ISSUE THREAD

**Issue by jpreese** [ardanlabs/service#189]
Noticed during a rolling update that communication to the Pod was briefly disrupted. After some digging found this discussion: https://github.com/kubernetes/kubernetes/issues/86280#issuecomment-583173036 which highlights the race condition between the app closing the listener and Kubernetes actually disallowing connections to go to the service.

Shutdown line here for reference: https://github.com/ardanlabs/service/blob/master/app/services/sales-api/main.go#L259

Assuming that this is indeed the root cause, we should implement one of the three approaches listed in the linked issue.

Additionally, looking through the linked blog post in the issue (https://freecontent.manning.com/handling-client-requests-properly-with-kubernetes/) they reference removing keep-alive connections towards the bottom which seems can be controlled via: https://pkg.go.dev/net/http#Server.SetKeepAlivesEnabled

**Comment by ardan-bkennedy** [comment]
John, so we should set the SetKeepAlivesEnabled to false when we received a SIGTERM?

**Comment by ardan-bkennedy** [comment]
I hate these types of timing issues, K8s should see the rejection and reroute.  Having the readiness handler fail doesn't help since it can take 15 seconds (worse case) for it to be pinged.

**Comment by jpreese** [comment]
> John, so we should set the SetKeepAlivesEnabled to false when we received a SIGTERM?

I haven't played around with the behavior of `SetKeepAlivesEnabled` to know what impact it has when shutting down, but I've seen it used in at least one other example: https://github.com/MarioCarrion/todo-api-microservice-example/blob/main/cmd/rest-server/main.go#L168

At a minimum, it seems like the accepted approach is to add a [preStop](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks) hook in the Pod definition for the container that sleeps anywhere from 5 to 20 seconds based on the other timeouts that are configured. The alternative would be to include it as part of the shutdown sequence in the service itself, but then it feels like you're tying Kubernetes-specific needs into the service itself.

> I hate these types of timing issues, K8s should see the rejection and reroute. Having the readiness handler fail doesn't help since it can take 15 seconds (worse case) for it to be pinged.

I agree, I actually just learned this moments before I created the issue. Wasn't aware traffic could still go to a terminating Pod.

**Comment by ardan-bkennedy** [comment]
The idea is we wire in the preStop hook to a handler and when we receive that, start the shutdown sequence and have readiness start to return a non-200.  Might as well still include the SetKeepAlive stuff.

I don't know how to test this?

**Comment by jpreese** [comment]
> The idea is we wire in the preStop hook to a handler and when we receive that, start the shutdown sequence and have readiness start to return a non-200. Might as well still include the SetKeepAlive stuff.
> 
> I don't know how to test this?

Unless I'm misunderstanding, I don't feel we need to create a handler for this. Catching `SIGTERM` accomplishes that for us. Additionally once we get to the `preStop`, traffic will naturally stop going to the Pod once Kubernetes syncs everything.

The problem as I see it is:
- The Pod receives a `SIGTERM`, letting it know to shutdown.
- The service _immediately_ calls `http.Shutdown()` which stops listening for traffic. However, its possible that Kubernetes hasn't yet removed the Pod from the available set of endpoints to route traffic to. Causing traffic to get routed to the Pod, and dropped.

The solution is:
- The Pod receives a `SIGTERM`, letting it know to shutdown.
- We add a `preStop` hook to the Pod that `sleeps` for 5-20 seconds which allows Kubernetes time to sync and remove the Pod from the list of available endpoints
- After the sleep finishes, _then_ the `http.Shutdown()` code will execute -- stopping traffic after we have a reasonable level of confidence that traffic has stopped coming to us.

**Comment by ardan-bkennedy** [comment]
I see, ok, let's try this.  I will figure out how to configure the preStop hook today or tomorrow.

**Comment by jpreese** [comment]
I did just quickly try this and can confirm that without a delay/preStop hook and 2 replicas, when you delete one of the pods (which will send the `SIGTERM`) a few calls get dropped. Adding in the delay makes `curl` return all 200s.

```console
HTTP/1.1 200 OK
Date: Wed, 06 Oct 2021 13:46:17 GMT
Content-Length: 0

HTTP/1.1 200 OK
Date: Wed, 06 Oct 2021 13:46:17 GMT
Content-Length: 0

curl: (7) Failed to connect to test-service port 80 after 1 ms: Connection refused
curl: (7) Failed to connect to test-service port 80 after 1 ms: Connection refused
curl: (7) Failed to connect to test-service port 80 after 0 ms: Connection refused

HTTP/1.1 200 OK
Date: Wed, 06 Oct 2021 13:46:17 GMT
Content-Length: 0

HTTP/1.1 200 OK
Date: Wed, 06 Oct 2021 13:46:17 GMT
Content-Length: 0
```

Making the above requests by calling the service from within another Pod in the cluster.

**Comment by jpreese** [comment]
> Yea, at this point I wanted to keep things simple for the local dev environment. It's important to mention some of this stuff somewhere and set people up for success. We can add the preStop hook to the K8s config at the very least with a note.

Agreed. This repository taught me about `http.Shutdown` in the first place, and since we touch on Kubernetes here I think it's worth at least mentioning the race condition problem.

**Comment by embano1** [comment]
Just to add some context how this issue **might** be resolved in the future by the platform: https://twitter.com/a_sykim/status/1413492899258400770?s=20

**Comment by ardan-bkennedy** [comment]
I've been really slow lately :(   I can wire a handler to the preStop or run a script. Unless I put my own sleep before the call to Shutdown, nothing will cause the code to wait.

I don't know what this means?
>  The service code will not be executed until the preStop finishes.

I don't know how the preStop hook prevents the service code from calling Shutdown after receiving the SIGINT?

**Comment by ardan-bkennedy** [comment]
I think this is probably best configured in K8s, since this is a K8s issue

**Comment by ardan-bkennedy** [comment]
I'm not sure the GCP stuff is up to date, I would love a PR for this.

**Comment by jpreese** [comment]
I can put something together today!

**Comment by ardan-bkennedy** [comment]
Thanks!!!
