### ISSUE TITLE
Add CI Specification

### ISSUE THREAD

**Issue by nstogner** [ardanlabs/service#19]
Consider adding a CircleCI / TravisCI file.

**Comment by wyattjoh** [comment]
You could always use something like Concourse?

**Comment by ardan-bkennedy** [comment]
I reached out to Travis to see if they will give us an account. If they do, that would be awesome. I will look at Concourse!  Thanks @wyattjoh for the suggestion.

**Comment by johndopazo** [comment]
Jenkins is common.

**Comment by ardan-bkennedy** [comment]
I don't see that as a hosted solution.

**Comment by egonzo** [comment]
https://jenkins.ardanlabs.com

**Comment by ardan-bkennedy** [comment]
I have applied for an Educational Account with Travis. Fingers Crossed.

**Comment by jcbwlkr** [comment]
Closed in #87
