### ISSUE TITLE
question: why only add one goroutine in metrics every 100 requests?

### ISSUE THREAD

**Issue by mrkagelui** [ardanlabs/service#192]
in https://github.com/ardanlabs/service/blob/f6bfce2ee2c965d8a81c4c04febc335afdda9896/business/sys/metrics/metrics.go#L63-L65 if I'm reading correctly, the goroutine counter is incremented every 100 requests, is this accurate? if I'm not wrong, one new goroutine will be spawned upon receiving 1 request.

shouldn't it be like this?

```go
if v.requests.Value()%100 == 0 {
	v.goroutines.Set(int64(runtime.NumGoroutine()))
}
```

**Comment by mrkagelui** [comment]
Ahhh you’re too fast Bill! I’d be honored to be one of the contributors

**Comment by ardan-bkennedy** [comment]
Sorry. I had a change to sit down and look at it. It was a great catch. You can definitely add yourself to the list and I will merge it.

**Comment by ardan-bkennedy** [comment]
You're welcome. I'm glad it is helping!
