### ISSUE TITLE
CORS Headers aren't applied to OPTIONS calls

### ISSUE THREAD

**Issue by lgarciaaco** [ardanlabs/service#195]
When constructing the handler with CORS support:
```
	// Construct the mux for the API calls.
	apiMux := handlers.APIMux(handlers.APIMuxConfig{
		Shutdown: shutdown,
		Log:      log,
		Auth:     auth,
		DB:       db,
		Broker:   broker,
	}, handlers.WithCORS("*"))
```

All preflights OPTIONS should pass as intended in https://github.com/ardanlabs/service/blob/master/app/services/sales-api/handlers/handlers.go#L63, yet this only accepts the OPTIONS calls but it doesn't set the response headers needed for Cross-Origin Resource Sharing.

**Comment by ardan-bkennedy** [comment]
Good catch. Will close this and contrinue on the PR.
