### ISSUE TITLE
Lesson 3.4.4; Docker CPU restrictions & Windows WSL2

### ISSUE THREAD

**Issue by burhan** [ardanlabs/service#202]
A note on Windows & WSL2:

The CPU pinning UI for docker desktop is not available if you are using docker on Windows with the WSL2 backend. To make the equivalent change, you need to update the [`.wslconfig file`](https://docs.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig), and the entry to add is:

```
[wsl2]
processors=2
```

Not a bug, just a suggestion for the next update / readme / wiki

**Comment by ardan-bkennedy** [comment]
Thanks for this. Can you add this to the wiki please?

**Comment by burhan** [comment]
Updated https://github.com/ardanlabs/service/wiki/Requirements.

**Comment by ardan-bkennedy** [comment]
Brilliant and Thank You!
