### ISSUE TITLE
in foundation/worker, why is function used instead of an interface?

### ISSUE THREAD

**Issue by mrkagelui** [ardanlabs/service#207]
in https://github.com/ardanlabs/service/blob/74ac8d0b95276f6f6a24f249aebc3c64c2f00d03/foundation/worker/worker.go#L13-L21

a func is used, why not something like 

```go
type JobRunner interface {
	Run(ctx context.Context, traceID string, payload interface{})
}

// Worker manages jobs and the execution of those jobs concurrently.
type Worker struct {
	wg       sync.WaitGroup
	mu       sync.Mutex
	registry map[string]jobRunner
	running  map[string]context.CancelFunc
}
```

so that when we can register the whole handler, like
```go
type Handler struct {
	lg Logger
	store Store
}

func (h Handler) Run(ctx context.Context, traceID string, payload interface{}) {
	h.lg.Info("starting handling", traceID)
	h.store.Save(transform(payload))
	h.lg.Info("finish handling", traceID)
}

func main() {
	registry := map[string]worker.JobRunner{
		"scan-read": Handler{},
	}
	// start worker as needed...
}
```

is there a reason we don't do this?

**Comment by mrkagelui** [comment]
I mean, I know with this we can still do 
```go
type Handler struct {
	lg Logger
	store Store
}

func (h Handler) Run(ctx context.Context, traceID string, payload interface{}) {
	h.lg.Info("starting handling", traceID)
	h.store.Save(transform(payload))
	h.lg.Info("finish handling", traceID)
}

func main() {
	h := Handler{}
	registry := map[string]worker.JobFunc{
		"scan-read": h.Run,
	}
	// start worker as needed...
}
```

is memory footprint the primary concern? or is there any other concurrency issue with using an interface? or dynamic dispatching performance issue?

**Comment by ardan-bkennedy** [comment]
An interface is overkill here. Remember, now you are asking the use to declare a type and implement a method. Then a value of that type must be constructed. All that is needed here is a function. Reduces the amount of code and complexity needed to use the API.
