### ISSUE TITLE
Question: what is the relationship between the 1MB limit and "linking"

### ISSUE THREAD

**Issue by mroobert** [ardanlabs/service#208]
In the **foundation/keystore/keystore.go** we have:

<img width="757" alt="Screenshot 2021-12-01 at 19 19 02" src="https://user-images.githubusercontent.com/26720098/144282302-a5dbb95d-797e-4cee-846b-ae090c986cfb.png">
 
I don't get the logic behind this 1MB limit and the explanation with the "shenanigans like linking" argument. Some references about this reasoning?

Thx!

**Comment by typecampo** [comment]
Im pretty sure this is for protection. If you were to pass in /dev/random it would use all your memory.

**Comment by mroobert** [comment]
> Im pretty sure this is for protection. If you were to pass in /dev/random it would use all your memory. Looking closer, if you pass in /dev/random it would use a 1MB sample from /dev/random/. Without LimitReader, io.ReadAll will keep reading from /dev/random until you run out of mem.

Oh, you mean like if the io.ReadAll would not read a PEM file and would read something else like "/dev/random" you would have protection with the io.LimitReader to don't fill the memory with whatever that "/dev/random" contains (it could be a big file maybe).

**Comment by typecampo** [comment]
Yes exactly. This is also useful for reading a response body in http server with ReadAll. /dev/random on Linux just spits out random data forever. You could use /dev/random to overwrite your hard drive to "secure  wipe" it clean.

So I think here, hes saying 1MB is plenty big enough to read in the PEM file.
