### ISSUE TITLE
K8s Support

### ISSUE THREAD

**Issue by ardan-bkennedy** [ardanlabs/service#21]
We need to add support for deploying to k8s. @jcbwlkr has a great idea of giving students a droplet on DO with a k8s environment already setup. We don't need to teach installing k8s but deplopying to it. Though this has a cost per student in each class, it is minimal and worth it.

We need to setup a k8s image and have instructions for creating a student lab environment.
Then teach how to deploy.

**Comment by nstogner** [comment]
Side note: Might be easier and more production-esque to do a one-click managed kubernetes cluster on Google cloud.

**Comment by wyattjoh** [comment]
Just at a higher cost 😄. Alternative is to also just setup minikube.

**Comment by ardan-bkennedy** [comment]
This is where I am very clueless. But cost must be factored in.

**Comment by nstogner** [comment]
I like minikube! It just has less of the wow factor that you get from deploying to THE CLOUUD

**Comment by wyattjoh** [comment]
I think the wow-factor is restored when you tell them that they just installed k8s on their local machine :P. Combine that with the fact that minikube works wonders with [xhyve](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#xhyve-driver), they don't even need Virtualbox.

**Comment by ardan-bkennedy** [comment]
When you guys decide to start speaking english, let me know. LOLOL

We need to figure this out.

**Comment by johnharris85** [comment]
Closing this as this has been broken out into #32, #33 & #34.
