### ISSUE TITLE
When using ipv4 and ipv6 this method fails

### ISSUE THREAD

**Issue by jffp113** [ardanlabs/service#222]
When using ipv4 and ipv6 this method fails because there is two json objects concated in the same output.

{"HostIp":"0.0.0.0","HostPort":"49190"}{"HostIp":"::","HostPort":"49190"}

https://github.com/ardanlabs/service/blob/f0950c72e9d4c3160936d124025dfddbb1cc2c4f/foundation/docker/docker.go#L76

**Comment by ardan-bkennedy** [comment]
I remember fixing this with older code. How do I get Docker to show IPv6 addresses?

**Comment by jffp113** [comment]
I don't know how to activate IPv6.
Regarding the fix, in my project it gives the following error:
`could not extract ip/port: could not decode json: invalid character '{' after array element`

But I will investigate a bit more,

Thx for your time.

**Comment by ardan-bkennedy** [comment]
My guess trying to make this an array of two documents failed. I will try something else.

**Comment by ardan-bkennedy** [comment]
I moved the code for adding the array syntax. Maybe this placement will work better?

**Comment by ardan-bkennedy** [comment]
I figured out how to turn it on. Now I can fix it.

**Comment by ardan-bkennedy** [comment]
Ok, try this new version of the docker code.
