### ISSUE TITLE
Using delve debugger

### ISSUE THREAD

**Issue by azdanov** [ardanlabs/service#230]
Hello!

What would be the correct way of using a [delve](https://github.com/go-delve/delve) or [goland debug](https://www.jetbrains.com/help/go/debugging-code.html) in the k8s environment?

I've read [some articles](https://golangforall.com/en/post/go-docker-delve-remote-debug.html) online about remote debugging and became curious about an "official" approach aligned with the rest of the service repo.

 Amazing project by the way, with lots of stuff to learn. Thanks for making it. 🙂

**Comment by ardan-bkennedy** [comment]
This is an amazing question.  Derek Parker has some video content on debugging in a container. He is actually teaching classes for Ardan about Delve.

YouTube Content:
https://www.youtube.com/playlist?list=PLADD_vxzPcZBe08-FpTfdgaLwU51X7ooE

Free Event Aug 31st:
https://www.ardanlabs.com/live-training-events/debugging-go-programs-containers-aug-31-2022.html
