### ISSUE TITLE
Broken URL https://education.ardanlabs.com/

### ISSUE THREAD

**Issue by ao10** [ardanlabs/service#233]
Hey team, I wanted to see the recorded video but it looks like there's a broken URL linked in the README here:

https://github.com/ardanlabs/service#purchase-video:~:text=education.ardanlabs.com

**Comment by cip8** [comment]
Hey ao10 👋

I think the new URL for the education page is here: https://www.ardanlabs.com/education/

The supporting videos for this service: https://www.ardanlabs.com/training/ultimate-go/service/

You can sign up for the Ultimate Go course here: https://www.ardanlabs.com/training/ultimate-go/

Have a great day!!
