### ISSUE TITLE
adopters?

### ISSUE THREAD

**Issue by 144mb** [ardanlabs/service#235]
> web service starter kit

As this project (and surrounding services like training and consulting) is meant to be a "web service starter kit", how about adding a list of adopters that have built real world projects on top of it?

For example via an `ADOPTERS` file to which orgs and individuals can add their projects? (Examples for ADOPTERS files: [Example 1](https://github.com/openfaas/faas/blob/master/ADOPTERS.md) , [Example 2](https://github.com/knative/community/blob/main/ADOPTERS.MD). )

Being able to point to such references / success stories helps a lot in internal discussions (at work, etc) about making tech stack and vendor decisions. References are a really important thing in Enterprise IT.

(And other suggestion: I'd love to see a couple of customer success stories (PR articles) about the service repo (and related paid services) on your company website. Similar to those about Go on the Go homepage. This kind of stuff really helps those who advocate in an org to try to use something new).

**Comment by ardan-bkennedy** [comment]
Hi. This is an interesting idea. I am not sure how many companies can publish this, but I will add that second example and ask a client people if they are comfortable doing this.
