### ISSUE TITLE
business/sys/database: wrong argument type passed to sqlx.Named()

### ISSUE THREAD

**Issue by nilsocket** [ardanlabs/service#242]
sqlx.Named expects an argument of type `any`, but []any is passed from function `queryString()`.

When `queryString()` is called with a slice as argument it pancis.

Minimal reproducible example with `sqlx.Named()`
```go
func main() {
	data := []struct {
		ID    int64  `db:"id"`
		Value string `db:"value"`
	}{
		{1, "one"},
		{2, "two"},
	}

	q := `INSERT INTO tempo (id, value) VALUES (:id, :value)`

	// nq, s, err := sqlx.Named(q, []any{data}) // panics
	nq, s, err := sqlx.Named(q, data) // works
	if err != nil {
		log.Println(err)
	} else {
		fmt.Println(nq, s)
	}
}
```

**Comment by ardan-bkennedy** [comment]
Is this because of that new functionality accepting a slice with an IN clause?

**Comment by ardan-bkennedy** [comment]
You are saying this should be just `args any`
```
// queryString provides a pretty print version of the query and parameters.
func queryString(query string, args any) string {
```

**Comment by ardan-bkennedy** [comment]
Ok, I made this change and ran the tests
https://github.com/ardanlabs/service/commit/987fa70b95d72ad12b0e2537d69492cfc26749c7

Please let me know if this is what you are talking about. This does make sense.

**Comment by nilsocket-w1** [comment]
@ardan-bkennedy Sorry for the late reply.
The change which you have made is what I was looking for.

Thank you.
