### ISSUE TITLE
foudation/worker: why is sem a "chan bool"?

### ISSUE THREAD

**Issue by mrkagelui** [ardanlabs/service#255]
https://github.com/ardanlabs/service/blob/7e1bf78aa7f91ccf59018d5f993d0d9214b80ec7/foundation/worker/worker.go#L21 for a semaphore, why do we want `chan bool` while `chan struct{}` would suffice?

**Comment by ardan-bkennedy** [comment]
When you will be sending data through a channel and the data itself if arbitary, use bool.

**Comment by mrkagelui** [comment]
> When you will be sending data through a channel and the data itself if arbitary, use bool.

yes, but in this case, we want to just use the "boundedness" of the channel right? shouldn't we use `struct{}`? we don't care what goes in or out of the channel itself for a semaphore

**Comment by ardan-bkennedy** [comment]
If the channel is only going to be closed, then use the empty struct. This is a good idiomatic way to represent this is the only behavior against the channel which essentially means it's used for just shutting down.

In the case of the sem channel, we need to send a value into the channel and the value is arbitrary. So I'm using bool.

**Comment by mrkagelui** [comment]
> If the channel is only going to be closed, then use the empty struct. This is a good idiomatic way to represent this is the only behavior against the channel which essentially means it's used for just shutting down.
> 
> In the case of the sem channel, we need to send a value into the channel and the value is arbitrary. So I'm using bool.

sorry for repeatedly coming back to this, are we really using the value in the channel? the only place I see it being used is https://github.com/ardanlabs/service/blob/7e1bf78aa7f91ccf59018d5f993d0d9214b80ec7/foundation/worker/worker.go#L99, and if I understand "semaphores", we primarily use a channel here so that "if we can read from the channel, we know that there's some capacity, the rest of the logic can continue". in other words, the gist is "to read from the channel", whatever comes out of it does not matter. please let me know if I'm misunderstanding this.

**Comment by ardan-bkennedy** [comment]
We are NOT using the value as I stated a few times. The value itself is arbitary, but we need a value none the less. SO, since a value needs to be sent, using the empty struct (which semanitcally is not a value) doesn't create the best semantic in this situation. The general rule is, if you are just going to be closing the channel, use the empty struct, show nothing will be send or recevied. If you are going to be sending a value into the channel, and the value itself is meaningless, use a bool.

**Comment by mrkagelui** [comment]
I see. hmm, in a similar setting, to implement a "set", e.g, to tell if an integer is in a collection of integers, would you use `map[int]bool`, or `map[int]struct{}`? would the size of that collection matter in this decision?

**Comment by ardan-bkennedy** [comment]
That is an excellent question. For a set I would use the empty struct. I know people who still want to use bool here.  I wouldn't make a decision based on the amount of memory being used here. I would make a decision based on readability.

**Comment by mrkagelui** [comment]
cool. I would use empty struct there too.
