### ISSUE TITLE
Question: why value semantics in worker mutex?

### ISSUE THREAD

**Issue by mrkagelui** [ardanlabs/service#265]
Hi, one of the most valuable lesson I've learned in your teaching is consistent semantics for a given struct, but for mutexes, [the source code](https://pkg.go.dev/sync#RWMutex.Lock) uses pointer semantics, why does [the worker package](https://github.com/ardanlabs/service/blob/dad2b38f35da5a1383c2690f6a37de91384e5047/foundation/worker/worker.go#L20) use value semantics? is it because we don't want two worker structs possibly share a mutex?

**Comment by ardan-bkennedy** [comment]
When you make a copy of a mutex, the copy is a different mutex. Locking one copy doesn't lock the other.

The answer is not to use pointer semantics at the field level. Use value semantics for the mutex field and use pointer semantics for the struct.

Plus, once you have a mutex, the struct represents an API. Use pointer semantics for structs that represent an API.

**Comment by mrkagelui** [comment]
got it, I think that makes sense.
