### ISSUE TITLE
The Httptreemux mix Wildcards error

### ISSUE THREAD

**Issue by EarthIsAPrisonIfYouNotAwareCanNotOut** [ardanlabs/service#278]
If i want to set different wildcard to each path router like
```
x	app.Handle(http.MethodGet, version, "/products/:product_id", pgh.QueryByID, authen)
	app.Handle(http.MethodGet, version, "/products/:user_id", pgh.QueryByUserID, authen)
```
It will report `Wildcards [user_id] are ambiguous with wildcards [product_id]` error.

**Comment by ardan-bkennedy** [comment]
Yea, because this is the same route for the same Method. The only difference is the variable name.

You really want
`/products/:product_id/users/:user_id`

Or something like that.

**Comment by EarthIsAPrisonIfYouNotAwareCanNotOut** [comment]
I check out the product.QueryByUserID is in the product.go and not use in path route, is there any problem with it?

**Comment by ardan-bkennedy** [comment]
Each domain should have it's name in the route.  For the User based handlers, that route should be `/users/:user_id` and for the Product based handlers, that route should be `/products/:product_id`. If you wanted to get products and filter by user id, you would have. `/products?user_id=123`
