### ISSUE TITLE
[Question] Metrics processing flow with Prometheus and Grafana

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#319]
Hi Bill, 

I don't fully understand the metrics processing flow. Could you explain the relationship between the sales-api, metrics, prometheus, and grafana. Thanks.

**Comment by ardan-bkennedy** [comment]
Do you have access to the video training for this repo?

**Comment by nhaancs** [comment]
Yes, I purchased the Ultimate Go Bundle.

**Comment by ardan-bkennedy** [comment]
Then watch the service 4.1 class or better yet, I'm teaching the class the week of October 23rd. All of your questions will be addressed.
