### ISSUE TITLE
Add environment provisioning and setup

### ISSUE THREAD

**Issue by johnharris85** [ardanlabs/service#32]
We need to create a script / tool that will provision the Digital Ocean (for now) infra required and install kubernetes ready for the service to be deployed to:

- [ ] Create script to setup k8s automatically (probably a modified version of [this guide](https://www.digitalocean.com/community/tutorials/how-to-create-a-kubernetes-1-10-cluster-using-kubeadm-on-ubuntu-16-04)
- [ ] Create script (Terraform?) to provision the infra and bootstrap the above

**Comment by farrukhny** [comment]
I suggest to use KOPS it can be user in AWS, GCE and Digital Ocean also you can export to Terraform template. I can help to create a env if you give me more info, also here is a link to [KOPS](https://github.com/kubernetes/kops) and this is kops on Digital Ocean [tutorial](https://github.com/kubernetes/kops/blob/master/docs/tutorial/digitalocean.md) or you can export KOPS to Terraform template and bootstrap cluster via Terraform.

**Comment by nstogner** [comment]
I would lean towards using some sort of managed kubernetes cluster... looks like DO might even be coming out with one? https://blog.digitalocean.com/introducing-digitalocean-kubernetes/

**Comment by nstogner** [comment]
You don't necessarily need 1 cluster per student, each student could use their own namespace

**Comment by ardan-bkennedy** [comment]
This is no longer necessary
