### ISSUE TITLE
[Question] Advice on source code structure

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#320]
Hi Bill, 

We're developing a Condo Management system. Each condominium can have multiple blocks, each block can have multiple floors, and each floor can have multiple apartments (we call them 'units'). So, we have 4 business domains: 'condominium', 'block', 'floor', and 'unit'. How can we structure them? Could we treat them as if they are on the same level, or 'block', 'floor', and 'unit' are sub-packages inside the 'condominium' package? Thanks.

**Comment by nhaancs** [comment]
I appreciate that, but I'm afraid that I'm unable to join the video call (sorry). Could you share your idea here?

**Comment by ardan-bkennedy** [comment]
I haven't scheduled one yet, but if you are not interested in a call that's fine. I suggest you gain access to the service 4.1 video that we offer on the ArdanLabs website. It will answer all your questions. 

If you are interested in scheduling a video call send me an email at bill@ardanlabs.com. This is too complicated to write up.
