### ISSUE TITLE
[Questing] Asking about Token API 

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#321]
Hi Bill, 

I see the URL for the Token API is `http://localhost:3000/v1/users/token/54bb2165-71e1-41a6-af3e-7da4a0e1e2c1` with the key ID included. Is this used for users to log in? If so, how a user could know about the key ID? Thanks.

**Comment by ardan-bkennedy** [comment]
I left to messages on your other two issues.

**Comment by nhaancs** [comment]
I removed the 'kid' param on the route and used the ActiveKID config instead.
