### ISSUE TITLE
The Vault pod is not ready after I restart my computer

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#326]
Why does the Vault pod keep becoming not ready every time I restart my computer? To fix this, I have to delete the cluster and start it again. Thanks.
![Screenshot 2023-10-30 at 21 44 35](https://github.com/ardanlabs/service/assets/15848072/ba0d04ba-1485-4029-bd6a-8354b6811061)

**Comment by ardan-bkennedy** [comment]
Vault is very complicated. You have to start Vault, but it won't work until it's unsealed and inititalized. We decided to have the Sales-Api service do this in the initContainer. So, until the initContainer runs, Vault is useless. I believe we are using cluster level persisted storage for what we need to do to init the system and I would have expected that to help in the situation you are experiencing.

Beyond this information, I'm not sure.

**Comment by nhaancs** [comment]
Thanks. Are you experiencing the same situation? I'm not sure if this is a known issue of the project, or if have I done something wrong with my code.

**Comment by ardan-bkennedy** [comment]
I will run the project again shortly. Maybe I broke something in the past 24 hours.

**Comment by ardan-bkennedy** [comment]
The code is working. I did push changes if you want to run the latest.

**Comment by nhaancs** [comment]
Hi @ardan-bkennedy, 

I pulled your latest code and started the cluster, everything was ok. But after I restarted my Docker Desktop, the `dev-status` command  resulted as below:
![Screenshot 2023-10-31 at 10 33 24](https://github.com/ardanlabs/service/assets/15848072/c3ff4626-6c52-4f06-8a7a-d23b27b72c43)

**Comment by ardan-bkennedy** [comment]
Having sleeping on it I think the problem might be the order docker is restarting the containers. It's critical that vault is started before sales and there is time between the two. I made some changes to the apply to test things out. I just start the observability services without waiting first, then I start the vault, database, wait, sales.

I always bring down the cluster every night, but even when I just put my machine to sleep I don't have issues. I am curious why you are restarting docker?

**Comment by ardan-bkennedy** [comment]
Having sleeping on it I think the problem might be the order docker is restarting the containers. It's critical that vault is started before sales and there is time between the two. I made some changes to the apply to test things out. I just start the observability services without waiting first, then I start the vault, database, wait, sales.

I always bring down the cluster every night, but even when I just put my machine to sleep I don't have issues. I am curious why you are restarting docker?

**Comment by ardan-bkennedy** [comment]
Having sleeping on it I think the problem might be the order docker is restarting the containers. It's critical that vault is started before sales and there is time between the two. I made some changes to the apply to test things out. I just start the observability services without waiting first, then I start the vault, database, wait, sales.

I always bring down the cluster every night, but even when I just put my machine to sleep I don't have issues. I am curious why you are restarting docker?

**Comment by nhaancs** [comment]
I don't think putting the machine to sleep will cause the issue. I only ran into this situation when I shut down my computer and then started it again to continue my work. In other words, this issue happens as my Docker gets restarted. 
I clone the repository and develop my own project. So I don't want to start and delete the cluster too often because it takes time and I don't want old data in the database being reset.

**Comment by ardan-bkennedy** [comment]
Look at the changes to apply, this has sped up the time it takes to bring up the cluster.

I NEVER shut my machine down. Have you tried just putting your machine to sleep instead of shutting it down all the time?

I have a solution for the DB.  You can run the database outside the cluster and keep the volume around.

Read the dev-database-external.yaml file.

**Comment by nhaancs** [comment]
Yes, I think an external database will work. Just wonder if is there anything that we can do with Vault instead.

**Comment by ardan-bkennedy** [comment]
You don't need value. Use my in-memory keystore.

**Comment by nhaancs** [comment]
Yes,thanks
