### ISSUE TITLE
[Question] Where to put my custom logic

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#328]
If I want to limit the number of products that can be created by a user. For example, each user can create a maximum of 10 products. Where should I put the verify logic, in the app layer or in the business layer? Thanks.

**Comment by ardan-bkennedy** [comment]
That is business logic. App layer will validate the structure of the input. The business layer will validate the rules. 

What you are describing is a rule.

Please close this issue if its been resolved.

**Comment by nhaancs** [comment]
Thank you
