### ISSUE TITLE
Convert compose and provide k8s yaml deployment assets

### ISSUE THREAD

**Issue by johnharris85** [ardanlabs/service#33]
We need to create the relevant k8s yaml assets that will enable the service to be deployed to k8s, currently we're using the `docker-compose.yml` file to deploy locally.

**Comment by wyattjoh** [comment]
You could always do something like: https://github.com/kelseyhightower/hello-universe where you let the binary help deploy itself to k8s? That was pretty neat.

**Comment by johnharris85** [comment]
Ye we talked a little about this, but I think we want to try and get a balance between "not too much effort" and "not too much magic". This is cool (+ stuff like metaparticle) but imho falls under "too much magic".

**Comment by ardan-bkennedy** [comment]
Hi @johnharris85, we should also finalize a discussion on this.

**Comment by ardan-bkennedy** [comment]
This is no longer necessary.
