### ISSUE TITLE
Develop local k8s deployment plan

### ISSUE THREAD

**Issue by johnharris85** [ardanlabs/service#34]
DO droplet is the default for k8s environment deployment, however we should have an option for those who want to run locally.

**Comment by ardan-bkennedy** [comment]
Hi @johnharris85, I hope you are well. I think we decided to go with ACI on Azure. I am still not sure it getting MiniKube working locally doesn't have value. Would love to have a final disucssion on this.

**Comment by ardan-bkennedy** [comment]
This is no longer necessary.
