### ISSUE TITLE
Select layer to calculate decimal numbers

### ISSUE THREAD

**Issue by mrbardia72** [ardanlabs/service#355]
Calculate decimal numbers

I want to write a function that performs an operation on decimal numbers
Where should I put this function?(After calculating on decimal numbers, it stores it in the database)
Layer foundation
Layer business

**Comment by ardan-bkennedy** [comment]
Which packages need to use this function and what layer do they live in?

**Comment by mrbardia72** [comment]
A simple package with a few functions for working with decimal numbers
and sending values to the database layer

. If it is not complete, I will explain more

**Comment by ardan-bkennedy** [comment]
I would keep those functions with the packages that need them to start. If you need to copy/paste them into 3 or more packages, then let me know. I am assuming these are core business packages that need them?

**Comment by mrbardia72** [comment]
Yes, I guess it should be in the business layer
Because before being stored in Redis, decimal operations must be performed on the data

**Comment by ardan-bkennedy** [comment]
It might belong in the storage layer which means in could go in the `sqldb` package.

**Comment by mrbardia72** [comment]
Thank you
