### ISSUE TITLE
Write regex!

### ISSUE THREAD

**Issue by mrbardia72** [ardanlabs/service#360]
If we want to use regex
Should it be written in the path below?
`service/foundation/validate`

**Comment by ardan-bkennedy** [comment]
When you have these questions start with the "purpose" of the code. Without understanding the purpose, it's hard to answer.

**Comment by mrbardia72** [comment]
> When you have these questions start with the "purpose" of the code. Without understanding the purpose, it's hard to answer. 

When you have these questions start with the "purpose" of the code. Without understanding the purpose, it's hard to answer.

**Comment by ardan-bkennedy** [comment]
Was this a mistake? I don't understand.

**Comment by mrbardia72** [comment]
Oh, sorry, there was a mistake

Actually, I know how this code should be written
I just wanted to ask if the place where I should check regex is this part or not

**Comment by ardan-bkennedy** [comment]
I can't give you guidance on where to put it if I don't know the purpose of the code as it relates to the project. Saying you have a regex without telling me what and why you have this leaves blind

**Comment by mrbardia72** [comment]
For example, I want to check the user name (check means the regex) which has a special regex
I want to check the correctness of the username entered by the user

**Comment by ardan-bkennedy** [comment]
Then you would want a Name type in the user package that would be the type for the name field in the user model. That regex would be used in the Parse function for this Name type. 

Look at role.go in the core user package.
