### ISSUE TITLE
Naming files

### ISSUE THREAD

**Issue by mrbardia72** [ardanlabs/service#361]
I think it is better to name the files and folders as follows

usergrp ==> user_grp
homegrep ===> home_grp

  For better readability

**Comment by ardan-bkennedy** [comment]
I would not do this. Even though the compiler will let you, this is not idiomatic. The language uses the underscore to provide the compiler information such as,  `_test` for a test file and package. Another example is `_darwin` where you are specifying the OS.

There needs to be a unique package name and I think `grp` is small and solves the problem.
