### ISSUE TITLE
refine make built-in function allocates add len

### ISSUE THREAD

**Issue by mrbardia72** [ardanlabs/service#362]
https://github.com/ardanlabs/service/blob/master/foundation/validate/errors.go#L39

m := make(map[string]string)   ===> m := make(map[string]string,len(fe))

**Comment by ardan-bkennedy** [comment]
You could do this but it won't make any difference in the performance of the app. This is a failure condition, not normal path. Even if it was normal path, I think it's insignificant. If this came up in a profile, then for sure this needs to be done.

All that being said, if you want to provide a PR, I'll accept it.

**Comment by ardan-bkennedy** [comment]
Fixed by PR [363](https://github.com/ardanlabs/service/pull/363)
