### ISSUE TITLE
Break Project Down As Training Material

### ISSUE THREAD

**Issue by ardan-bkennedy** [ardanlabs/service#37]
I had started this repo quickly for a training earlier this year.

https://github.com/ardanlabs/srvtraining

I think the code needs to be broken down into consumable parts. It's hard in the classroom to copy and paste the code and clean it up. It would be nice to have exercises in between to allow people to get comfortable as you add more complexity.

Thoughts?

**Comment by nstogner** [comment]
I like the steps... They definitely add some work when something changes across steps, but its worth it i think.

**Comment by nstogner** [comment]
Probably need to stabilize this repo first?

**Comment by nstogner** [comment]
^ Currently a private doc, will open up once it gets somewhat coherent.

**Comment by huberts90** [comment]
Hi,
is it possible to see any doc or broken parts of project ? :) At first glance it's not easy to understand all concepts ?

**Comment by ardan-bkennedy** [comment]
Totaly get it. @jcbwlkr is doing that exact work, breaking it down. I will ask him to respond more. A big part of the class we teach is providing a mental model of the code.

**Comment by huberts90** [comment]
It would be great if I can see point of view and any descriptions by @jcbwlkr. Thank You in advance.

**Comment by jcbwlkr** [comment]
@huberts90 There is a separate repo https://github.com/ardanlabs/service-training that is still underway. It builds this project from scratch over several iterations.
