### ISSUE TITLE
user role question

### ISSUE THREAD

**Issue by himynamej** [ardanlabs/service#372]
in user put handler :
	app.Handle(http.MethodPut, version, "/users/{user_id}", hdl.update, authen, ruleAuthorizeUser)
user can update His own roles?

**Comment by ardan-bkennedy** [comment]
WOW, what a great catch. I have to think about this and review that possibility. Thanks for ruining my day.  Hahahahaha. JK

**Comment by ardan-bkennedy** [comment]
Send me an email @himynamej   bill@ardanlabs.com

**Comment by himynamej** [comment]
Ok my email is javadah1376@gmail.com

**Comment by ardan-bkennedy** [comment]
Added a new route for updating a role.
