### ISSUE TITLE
More complicated role

### ISSUE THREAD

**Issue by himynamej** [ardanlabs/service#374]
In My project we want to add more complicated roles for example for admin we want to add more control,one admin can update user one and enother admin can not do it .do you have any suggestions for us?

**Comment by ardan-bkennedy** [comment]
The framework is there with OPA. Just figure out on paper the semantics and then just extend the use of OPA and middleware functions. 

You might want to try and talk to some OPA people and see what they suggest.

**Comment by himynamej** [comment]
Thank you
