### ISSUE TITLE
Unit test

### ISSUE THREAD

**Issue by Ali-Farhadnia** [ardanlabs/service#378]
In business tests. Why is the result stored in the database not checked and only the result returned by the core API is tested?

for example in user update test:

func userUpdate(dbt *dbtest.Test, sd dbtest.SeedData) []dbtest.UnitTable {
	email, _ := mail.ParseAddress("jack@ardanlabs.com")

	table := []dbtest.UnitTable{
		{
			Name: "basic",
			ExpResp: userbus.User{
				ID:          sd.Users[0].ID,
				Name:        "Jack Kennedy",
				Email:       *email,
				Roles:       []userbus.Role{userbus.RoleAdmin},
				Department:  "IT",
				Enabled:     true,
				DateCreated: sd.Users[0].DateCreated,
			},
			ExcFunc: func(ctx context.Context) any {
				uu := userbus.UpdateUser{
					Name:            dbtest.StringPointer("Jack Kennedy"),
					Email:           email,
					Roles:           []userbus.Role{userbus.RoleAdmin},
					Department:      dbtest.StringPointer("IT"),
					Password:        dbtest.StringPointer("1234"),
					PasswordConfirm: dbtest.StringPointer("1234"),
				}

				resp, err := dbt.Core.BusCrud.User.Update(ctx, sd.Users[0].User, uu)
				if err != nil {
					return err
				}

				return resp
			},
			CmpFunc: func(got any, exp any) string {
				gotResp, exists := got.(userbus.User)
				if !exists {
					return "error occurred"
				}

				if err := bcrypt.CompareHashAndPassword(gotResp.PasswordHash, []byte("1234")); err != nil {
					return err.Error()
				}

				expResp := exp.(userbus.User)

				expResp.PasswordHash = gotResp.PasswordHash
				expResp.DateUpdated = gotResp.DateUpdated

				return cmp.Diff(gotResp, expResp)
			},
		},
	}

	return table
}

**Comment by ardan-bkennedy** [comment]
Everything gets check by virtual of running all the tests. Remember we seed the database and query. If there is no error on these create tests, I feel I can assume it's ok.

**Comment by Ali-Farhadnia** [comment]
Sorry i mean this https://github.com/ardanlabs/service/commit/a31dccbfd909f942f0e5746cace5cd47eee4e14d

**Comment by Ali-Farhadnia** [comment]
Thanks for clarifying, Bill.
