### ISSUE TITLE
layer called userapp!

### ISSUE THREAD

**Issue by mrbardia72** [ardanlabs/service#379]
Adding another layer called userapp, what exactly does it do?

Because we had three layers before and now another layer has been added called userapp

**Comment by himynamej** [comment]
Hey bardia , userapp is for separation To separate the protocol from the app part.for example you want to add grpc ,it's easy now

**Comment by ardan-bkennedy** [comment]
That's right. At some point I'm going to try to add a set of grpc endpoints and see how well the idea works.

**Comment by himynamej** [comment]
So good ,I want to add some htmx frontend it needs some handler ,it gonna help a lot

**Comment by mrbardia72** [comment]
@ardan-bkennedy @himynamej 
Oh, how good, I had asked such things before, here is the link
https://github.com/ardanlabs/service/issues/354#issue-2131640131
