### ISSUE TITLE
Package internal/mid imports internal/auth at the same level

### ISSUE THREAD

**Issue by arashbina** [ardanlabs/service#38]
Based on the blog post regarding [package oriented design](https://www.ardanlabs.com/blog/2017/02/package-oriented-design.html) packages in the same level inside internal should not be importing each other. However `mid` imports `auth` here. Is there a reason why this is ok? Thank you.

**Comment by ardan-bkennedy** [comment]
That Auth package belongs inside the platform folder, which would solve the problem. But there are exceptions to everything. Inside of internal we work very hard to never take this exception. But inside of platform it is impossible not to. Foundational packages tend to need other foundational packages.

**Comment by arashbina** [comment]
Thanks Bill. Created a PR to move `auth` from `internal` to `internal/platform`.
