### ISSUE TITLE
Add account verification link

### ISSUE THREAD

**Issue by mrbardia72** [ardanlabs/service#389]
Adding the account verification link when the user has registered and we want to email the account verification link

In which layer should we do this? userbus or userapp!

**Comment by himynamej** [comment]
You want to send email to user ,do it in userbus

**Comment by ardan-bkennedy** [comment]
It depends. I believe Auth is an app layer concern. The business layer shouldn't know anything about Auth. It should trust the App layer to not call into it unless it's ok. For sure you don't want to have Auth concerns in both layers. Account verification sounds like Auth to me so I would put it in the app layer.

**Comment by mrbardia72** [comment]
Thank you, I believed that it should be done in the app layer
But I said to consult
