### ISSUE TITLE
Pick a theme

### ISSUE THREAD

**Issue by jcbwlkr** [ardanlabs/service#39]
The material would be easier to digest if our main service wasn't simply `crud` and if we were manipulating records besides just `User`. Some ideas include:

- A TODO service where we are manipulating `Task` values.
- A veterinarian's office service where we have `Pet` values.
- A comic collector's database. Let people keep track of their `Comic`s.
- A garage sale manager. I want to know what `Product`s I have for sale in my garage, how much they cost, and who they came from. Many people do multi-family sales and it could be useful to know that item 12345 came from Cindy so the money should go to her.

We could probably come up with several and bikeshed this forever.

**Comment by ardan-bkennedy** [comment]
Yes, this would be better but we need to pick 1

**Comment by nstogner** [comment]
Garage sale manager +1

**Comment by jcbwlkr** [comment]
Yeah I am liking the garage sale idea. I will come up with a diagram of some of the models I want and then we can include that in the README

**Comment by jcbwlkr** [comment]
This is what I'm thinking:

![garage-sale](https://user-images.githubusercontent.com/2027263/45169494-f824e100-b1ba-11e8-80c4-80bbf1675975.png)

**Comment by jcbwlkr** [comment]
On `Product` the `Quantity` field is how many of this item we started with and the `Available` field is inferred by subtracting the sum of the quantity field from all related `Sale` records
