### ISSUE TITLE
Transaction error 500 when testing transaction with validation error 400

### ISSUE THREAD

**Issue by rmsj** [ardanlabs/service#391]
If a new test is added to the transaction api:

`func create400(sd apitest.SeedData) []apitest.Table {
	table := []apitest.Table{
		{
			Name:       "basic",
			URL:        "/v1/tranexample",
			Token:      sd.Admins[0].Token,
			Method:     http.MethodPost,
			StatusCode: http.StatusBadRequest,
			Input: &tranapp.NewTran{
				Product: tranapp.NewProduct{
					Quantity: 10,
				},
				User: tranapp.NewUser{
					Name:            "Bill Kennedy",
					Email:           "bill@ardanlabs.com",
					Roles:           []string{"ADMIN"},
					Department:      "IT",
					Password:        "123",
					PasswordConfirm: "123",
				},
			},
			GotResp: &tranapp.Product{},
			ExpResp: nil, //TODO,
			CmpFunc: func(got any, exp any) string {
				return nil // TODO
			},
		},
	}
	return table
}`

The error that transaction.go sends is a 500 error, overriding the 400 from the validation.
See transaction.go, line 40

PS.: Sorry, can't get format to behave.

**Comment by ardan-bkennedy** [comment]
I can reproduce this. Transactions have created all sort of chaos. I am looking into this now.  THANKS

**Comment by ardan-bkennedy** [comment]
Ok, I just pushed a fix. This was a great catch.
