### ISSUE TITLE
Question: API integration

### ISSUE THREAD

**Issue by belsakn** [ardanlabs/service#393]
Hello,

This is more of a request than a question.

First, I would like to express my appreciation for this repository. It looks great, and I thank you for sharing it.

I have a query regarding integrating a third-party API (whether external or internal). Would you approach this integration in the same way as you would with a database, or would you take a different approach?

Thank you for your response.

**Comment by himynamej** [comment]
Hey ,I work on a big project with this amazing structure,and I do what you said,yeah that's work great .

**Comment by ardan-bkennedy** [comment]
I tend to write packages for 3rd party APIs and foundational packages and then use them in a business package.  If the API is handling storage concerns, you could add them under stores. Do what you think is right and then evaluation over time.
