### ISSUE TITLE
Question about vproduct domain

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#405]
- Does the purpose of the vproduct domain is to supports query products API that can return user_name instead of getting user_name for each product in the product app layer as before, and also have ability to do sorting, filtering by user_name?
- What is the cost of create a db view, is it affect the performance?
- Can we create a view of tables in multiple database server?

Thank you.

**Comment by ardan-bkennedy** [comment]
All of this is covered in the video and we have scholarships.

https://www.ardanlabs.com/training/individual-on-demand/ultimate-go-bundle/

TL;DR

* The purpose it to provide support for access cross-domain data points in a unified data model. This allows support for sorting and filtering.

* The cost is nothing to create the view. The only problem with a view is they can't be special purpose indexed.

* A view lives in a single database. Normally for a project like service there is only 1 database server instance. Schema's or naming conventions can be used to isloate domain related tables.

In the end, you do not want to do cross-domain joins in Go. Do that stuff in the DB via views or even stored procedures.

**Comment by nhaancs** [comment]
Thank you
