### ISSUE TITLE
Question about pointer semantic

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#411]
Why do you use the pointer semantic for this method, I see other methods are using value semantic. Thank you.

`func (app *UpdateProduct) Decode(data []byte) error {`

https://github.com/ardanlabs/service/blob/95936c2a93a344714d5a9a4160090baf7dbbea81/app/domain/productapp/model.go#L75

**Comment by ardan-bkennedy** [comment]
This method is implementing an interface and it must have shared access to the NewProduct value in order to mutate the value. There is no other choice but to use pointer semantics in this situation.
