### ISSUE TITLE
Question about logger

### ISSUE THREAD

**Issue by nhaancs** [ardanlabs/service#412]
I see that slog have the `With` method, which returns a new logger with some appended attributes. But in the logger package you haven't implemented this one. I wonder about the reason of this dicision, is it an anti pattern or you just dont need this method.

Thank you.

**Comment by ardan-bkennedy** [comment]
I customized slog to meet some of me personal choices. The things I need are hardcoded in the implementation details. If I was look to extend slog, but still keep it available for others to use and customize, I would have done things differently.
