### ISSUE TITLE
Leaking unnecessary internals of the system to clients

### ISSUE THREAD

**Issue by ameghdadian** [ardanlabs/service#429]
When something goes wrong in the process of decoding request payload, I assume unnecessary information about the system internals are exposed to clients(UI layer).

Specifically, I would like to point to this section of the code:

```go
func Decode(r *http.Request, v Decoder) error {
	data, err := io.ReadAll(r.Body)
	if err != nil {
		return fmt.Errorf("request: unable to read payload: %w", err)
	}

	if err := v.Decode(data); err != nil {
		return fmt.Errorf("request: decode: %w", err)     // <<<<<<< HERE >>>>>>>>
	}

	if v, ok := v.(validator); ok {
		if err := v.Validate(); err != nil {
			return err
		}
	}

	return nil
}
```

Here you can find a sample HTTP response you get when this case happens:

```json
{
  "error":"unable to decode payload: json: cannot unmarshal number into Go struct field AppNewUser.phoneNumber of type string"
}
```
\
Is this considered a security issue? 
If so, can we address the problem in a way the information is kept private?

**Comment by ardan-bkennedy** [comment]
Good question. It really depends on the project, company, and how/where it is being deployed. You need some balance between giving the user the information they need to know why this failed on data validation. The problem with altering this message is it's a lot of work to try and change individual messages.
