### ISSUE TITLE
Flag package incompatible with non-flag arguments

### ISSUE THREAD

**Issue by nstogner** [ardanlabs/service#43]
Appear unable to do: `go run main.go something.txt` ... i.e. reading a standard non-flag argument b/c a call to `flag.Process` errors out on the `default`:

*internal/platform/flag/flag.go*
```go
		switch {
		case strings.HasPrefix(osArg, "-test"):
			return nil
		case strings.HasPrefix(osArg, "--"):
			flag = osArg[2:]
		case strings.HasPrefix(osArg, "-"):
			flag = osArg[1:]
		default:
			return fmt.Errorf("invalid command line %q", osArg)
		}
```

**Comment by ardan-bkennedy** [comment]
Ok, I will look at this during the week.

**Comment by ardan-bkennedy** [comment]
Question, for a service this is not valid syntax and we want a flag system in place. So why can't thaty be

```go run main.go -f something.txt```

Plus, why are you using `go run` :)

**Comment by nstogner** [comment]
Agreed for service... but for cli tools it makes sense to have non-flag inputs

**Comment by ardan-bkennedy** [comment]
Flage package has been replaced.
