### ISSUE TITLE
Request for Lazy Transaction Initialization in BeginCommitRollback Middleware

### ISSUE THREAD

**Issue by mscno** [ardanlabs/service#431]
Hi, I'm using your BeginCommitRollback middleware in an app with conditional transaction needs.
First off, I want to say that the current implementation is really smooth and works great!
Is it possible to modify the middleware to initialize transactions lazily?
Ideally, the transaction would only start when GetTran is called (i.e., for handlers using .newWithTx).
This would avoid starting unnecessary transactions for endpoints that don't require them.
Any guidance or thoughts on implementing this would be greatly appreciated. Thanks!

**Comment by ardan-bkennedy** [comment]
If you only apply the middleware at the route level that would make it only applicable for that route.

Are you saying a given route may or may not need to be in a transaction?

**Comment by mscno** [comment]
I am using the middleware in a RPC based API. And most of the RPC frameworks (GRPC, ConnectRPC etc) make it tricky yto define middleware at the route level, they typically only allow definition of middleware at the service level. 
So in my case I have `service A`, which has methods `M1` and `M2`, where M1 needs `tx` support, while M2 doesnt not. Adding the middleware at service A, allows me to call `.newWithTx()` to dynamically swap the bus/stores with the `tx` backed versions and use the `tx` in `ctx`, by getting it with `GetTran()`. But for M1, where I dont use the tx object in ctx, I still start and commit an "empty transaction" for all method calls to `M1` route.

**Comment by ardan-bkennedy** [comment]
My first thought is to somehow pass state to the Tx middleware function to just return or not. Maybe in the context. The problem is that middleware function will execute before the app layer function. 

My next thought is maybe you have two different muxes handling traffic. The one that needs Tx and the one that don't. Then you can set different global middleware.

Then you have the mux that actually accepts the traffic. The handlers basically proxy one of the other two muxes.

**Comment by mscno** [comment]
Thanks the the input and suggestions. I ended up wrapping the tx in a LazyTx struct. The LazyTx struct is embedded in every request. But transaction is not started until GetTran is called.

```

type lazyTx struct {
	bgn    pg.Beginner
	tx     pg.CommitRollbacker
	mu     sync.Mutex
	ctx    context.Context
	inited bool
}

func (l *lazyTx) init() error {
	l.mu.Lock()
	defer l.mu.Unlock()

	if l.inited {
		return nil
	}

	slog.Info("BEGIN TRANSACTION")
	tx, err := l.bgn.Begin(l.ctx)
	if err != nil {
		return fmt.Errorf("BEGIN TRANSACTION: %w", err)
	}

	l.tx = tx
	l.inited = true
	return nil
}

func (l *lazyTx) Commit() error {
	l.mu.Lock()
	defer l.mu.Unlock()

	if !l.inited {
		return nil
	}

	slog.Info("COMMIT TRANSACTION")
	return l.tx.Commit(l.ctx)
}

func (l *lazyTx) Rollback() error {
	l.mu.Lock()
	defer l.mu.Unlock()

	if !l.inited {
		return nil
	}

	slog.Info("ROLLBACK TRANSACTION")
	err := l.tx.Rollback(l.ctx)
	if errors.Is(err, pgx.ErrTxClosed) {
		return nil
	}
	return err
}

// ConditionalBeginCommitRollback executes the transaction middleware functionality.
func ConditionalBeginCommitRollback(bgn pg.Beginner) connect.UnaryInterceptorFunc {
	return func(next connect.UnaryFunc) connect.UnaryFunc {
		return connect.UnaryFunc(func(
			ctx context.Context,
			req connect.AnyRequest,
		) (connect.AnyResponse, error) {
			ltx := &lazyTx{
				bgn: bgn,
				ctx: ctx,
			}

			ctx = setLazyTran(ctx, ltx)

			resp, err := next(ctx, req)

			if ltx.inited {
				if err != nil {
					if rbErr := ltx.Rollback(); rbErr != nil {
						slog.Info("ROLLBACK TRANSACTION", "ERROR", rbErr)
					}
				} else {
					if cmtErr := ltx.Commit(); cmtErr != nil {
						return nil, connect.NewError(connect.CodeInternal, fmt.Errorf("COMMIT TRANSACTION: %w", cmtErr))
					}
				}
			}

			return resp, err
		})
	}
}

func setLazyTran(ctx context.Context, ltx *lazyTx) context.Context {
	return context.WithValue(ctx, lazyTrKey, ltx)
}

// GetLazyTran retrieves the value that can manage a transaction.
func GetLazyTran(ctx context.Context) (pg.CommitRollbacker, error) {
	v, ok := ctx.Value(lazyTrKey).(*lazyTx)
	if !ok {
		return nil, errors.New("transaction not found in context")
	}

	if err := v.init(); err != nil {
		return nil, err
	}

	return v.tx, nil
}
```

**Comment by ardan-bkennedy** [comment]
Nice. I am glad you figured out a solution.
