### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by ameghdadian** [ardanlabs/service#441]
Hi!

I've been looking into the project and I noticed that upon successful creation of a resource, we conclude the request with `HTTP 200(OK)` response.

First, I'd like to propose using `HTTP 201`[(CREATED)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201#:~:text=The%20HTTP%20201%20Created%20successful%20response%20status%20code%20indicates%20that%20the%20HTTP%20request%20has%20led%20to%20the%20creation%20of%20a%20resource.) status code when creating a resource.

Next, when implementing `web.Encoder` interface, repetition of Content-Type(e.g.,  `application/json`) might lead to some typos overtime. Shall we have a separate file inside `foundation/web` package that provides these types as constants? If so, I'd be happy to contribute.

**Comment by ardan-bkennedy** [comment]
It's been my experience using 201 is unnecessary and doesn't really add any value. If you want to do that then implement the httpStatus interface for that data model.

The idea to have support for the code used inside the encode methods is interesting. All the code could be provided in a web.JsonEncode function. 

Let me think about that more.

**Comment by ameghdadian** [comment]
> If you want to do that then implement the httpStatus interface for that data model.

There is a drawback with this approach. By implementing `httpStatus` interface, not only the "create" handler, but any other handlers(e.g., "query" and "update") returning that data model will be affected.

I think when we moved `ResponseWriter` object out of handlers, we've got the advantage of having only a single place to deal with the returned status code, but we've lost the flexibility to fine-tune status codes at the handler level.
To stay with what we have now, I would suggest to add some modifications to `web.Respond` function, to take different HTTP operations into account. It would look something like this:

```go
func Respond(ctx context.Context, w http.ResponseWriter, r *http.Request, dataModel Encoder) error {
        ...
	
	var statusCode int
	
        // Standard status codes provided the operation is successful
	switch r.Method {
	case http.MethodPost:
                statusCode = http.StatusCreated
        case http.MethodPut:
                statusCode = http.StatusOK
         
         ...
        }

        // Overwrite status code if any of following applies
	switch v := dataModel.(type) {
	case httpStatus:
	        statusCode = v.HTTPStatus()

	case error:
		statusCode = http.StatusInternalServerError

	default:
		if dataModel == nil {
			statusCode = http.StatusNoContent
		}
	}
        
        ...
}
```

**Comment by ardan-bkennedy** [comment]
This doesn't solve the problem of giving the user flexibility to use 200 or 201 or any status when returning a non-error value.

let me think about this more.

**Comment by ardan-bkennedy** [comment]
If I needed to set the create to 201, I think this is what I would do.

```
type User struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	Roles        []string `json:"roles"`
	PasswordHash []byte   `json:"-"`
	Department   string   `json:"department"`
	Enabled      bool     `json:"enabled"`
	DateCreated  string   `json:"dateCreated"`
	DateUpdated  string   `json:"dateUpdated"`
	status       errs.ErrCode
}

func (app User) HTTPStatus() int {
	return app.status.Value()
}

func toAppUser(bus userbus.User, errCode errs.ErrCode) User {
```

Keep this logic in the app layer. Implements the interface and uses the `to` function to set the status you want to use. I would add the `Created` error code.

Now that being said. You could make changes to the web package to hide this a bit more. This project and no project I work on uses the 201 for create. I think it complicates things for no real necessary reason.
