### ISSUE TITLE
FieldErrors rendered as "Internal Server Error" 

### ISSUE THREAD

**Issue by ameghdadian** [ardanlabs/service#443]
`FieldErrors` results in 500 status code being rendered for two reasons:

1. `Errors` middleware explicitly looks for `errs.Error` type and if not found, returns 500 status code,
2.  `httpStatus` interface is not yet implemented for `FieldErrors`, therefore `case error:` switch case inside `web.Response` wins and results in `Internal Server Error`.

**Comment by ardan-bkennedy** [comment]
You are right if a raw FieldErrors is returned, but that actually never happens.

```
func (a *app) create(ctx context.Context, r *http.Request) web.Encoder {
	var app NewHome
	if err := web.Decode(r, &app); err != nil {
		return errs.New(errs.InvalidArgument, err)
	}
```

We always convert errors into errs.Error in the app layer. So if this failed you would get the following under a 400.

```
validate: [{\"field\":\"type\",\"error\":\"type is a required field\"},{\"field\":\"address1\",\"error\":\"address1 is a required field\"},{\"field\":\"zipCode\",\"error\":\"zipCode is a required field\"},{\"field\":\"city\",\"error\":\"city is a required field\"},{\"field\":\"state\",\"error\":\"state is a required field\"},{\"field\":\"country\",\"error\":\"country is a required field\"}]
```

This is why you don't need the interfaces being implemented or any reference of this error type in the middleware.

**Comment by ardan-bkennedy** [comment]
IMHO, you want to catch any error that is not an errs.Error flowing into the middleware and web package. You want to control everything running through the system. If you found something get through, you would want to fix it.

**Comment by ameghdadian** [comment]
Thank you Bill.

So do we need to modify what's returned from `query` handlers in `service` project, as they're returning `FieldErrors` in some scenarios. Here's two instances where this happens: `[User App layer](https://github.com/ardanlabs/service/blob/cbf46d058a05e8bbb0892ba76f71de8fe0be6749/app/domain/userapp/userapp.go#L111) or [Product App layer](https://github.com/ardanlabs/service/blob/cbf46d058a05e8bbb0892ba76f71de8fe0be6749/app/domain/productapp/productapp.go#L83).
```go
func (a *app) query(ctx context.Context, r *http.Request) web.Encoder {
	qp, err := parseQueryParams(r)
	if err != nil {
		return errs.New(errs.InvalidArgument, err)
	}

	page, err := page.Parse(qp.Page, qp.Rows)
	if err != nil {
		return errs.NewFieldsError("page", err)
	}

	filter, err := parseFilter(qp)
	if err != nil {
		return err.(errs.FieldErrors)
	}
```

If any changes is required, I'm open to help with that.

**Comment by ameghdadian** [comment]
I've just created this [PR](https://github.com/ardanlabs/service/pull/444) to address the issue. Please feel free to make any modifications as needed.

**Comment by ardan-bkennedy** [comment]
Nice catch.

I think the change needs to be for that NewFieldsError to return an errs.Error with the field error wrapped. To fix the other to type assert to errs.Error

let me look at this today.

**Comment by ameghdadian** [comment]
Another thing worth mentioning is that. with `parseFilter` functions parsing query parameters, we're informing users the corrections they need to make, only one piece at a time.

I'd like to know your perspective on this and whether we can start with an uninitialized `FieldErrors` first, append all errors(if any) and then return it.

**Comment by ardan-bkennedy** [comment]
That should be fixed. We can check everything and return a fields error with everything

**Comment by ardan-bkennedy** [comment]
Ok, this commit fixes the problem.

https://github.com/ardanlabs/service/commit/2aa9a2cf119e2fe400303b2e847f96caf82cb82f

**Comment by ameghdadian** [comment]
IMHO, we're probably going to have a problem with the new changes. The problem is that `parseFilter` function returns `FieldErrors` and the `App` layer calling it, expects to see `errs.Error` but finds none. 

I'm also concerned that `NewFieldsError` is returning something other than what it claims, and this could open the door for API misuse. In other words, users have access to both `FieldErrors` and its constructor, they can pick whichever they prefer, but the final outcome differs.

I appreciate your insight about this.

**Comment by ameghdadian** [comment]
I think we can also change this line to only use `NewFieldsError`:

https://github.com/ardanlabs/service/blob/2aa9a2cf119e2fe400303b2e847f96caf82cb82f/app/domain/authapp/authapp.go#L29

**Comment by ardan-bkennedy** [comment]
Good catch. Actually since NewFieldsError returns an *errs.Error, we don't need the extra wrapping.

NewFieldsError is returning an error that is shaped as a FieldsError, and I think that is fine. In the end we want to keep things simple and be returning an *errs.Error.

**Comment by ardan-bkennedy** [comment]
Shoot, how did I miss that. The tests passed and I am sure I have some error tests for this?

**Comment by ardan-bkennedy** [comment]
We agree the parseFilter function must return an `error`. We can't walk away from this idiom.

We want a `FieldsError` with multiple reported problems when calling `parseFilter`

We need an `*errs.Error` because that is what implements the encoder interface.

I think this commit provides the solution.

https://github.com/ardanlabs/service/commit/d818ca8ca52e0237701b0b5b57fa0938a15f48ab

I really would like to have just the 1 error type that implements the encoder interface. This better controls what can flow through the system as it related to errors.

**Comment by ardan-bkennedy** [comment]
We need some tests to cover query filters. I though I had them so when the tests passed I thought I was good. What a classic mistake :(

**Comment by ameghdadian** [comment]
Thank you for sharing your insights. Much appreciated!

I also suspect we intended to name `FieldErrors`' constructor as `NewFieldErrors`.

**Comment by ardan-bkennedy** [comment]
I was looking at that and I think you are right for consistency. Why don't you give me a PR for this to get your name in the contributors.

**Comment by ameghdadian** [comment]
Surely.

[Here](https://github.com/ardanlabs/service/pull/447) you can find the related PR. Additionally it sorts out the filter validation problem of `vproductapp`.
