### ISSUE TITLE
pull access denied for sales-api

### ISSUE THREAD

**Issue by aminmeyghani** [ardanlabs/service#51]
Just curious, is the `sales-api` accessible, because I'm getting the following after running `make up`:

```
pull access denied for sales-api-amd64, repository does not exist or may require 'docker login'
```

Thanks

**Comment by ardan-bkennedy** [comment]
I am not a Docker guru but I am talking to the team now about your message.

**Comment by aminmeyghani** [comment]
Yup, that was it, thanks.
