### ISSUE TITLE
Integrate Authz OPA - Open Policy Agent

### ISSUE THREAD

**Issue by farrukhny** [ardanlabs/service#55]
I think it will be good if we can add authz into the service. I think this is important part of any system and OPA is really interesting product and it is part of CNCF and OPA has integration with lot of popular product like Kubernetes and isto etc.

OPA is a lightweight general-purpose policy engine that can be co-located with service.

[https://www.openpolicyagent.org](https://www.openpolicyagent.org)

**Comment by jcbwlkr** [comment]
Hi, @farrukhny! Thanks for the suggestion. That project does look very nice and would certainly be a nice addition for many services, however it is out of scope for this class.
