### ISSUE TITLE
Use official docker client instead of os/exec

### ISSUE THREAD

**Issue by tchaudhry91** [ardanlabs/service#57]
Specifically talking about `internal/platform/docker/docker.go`
I see that we use os/exec to pipe out commands to docker. This works right now, but if commands start getting more complex, it's going to get dirty.
Docker has an excellent official client which I believe would make this a lot cleaner. The README claims that docker is going to be an integral part. If so, I think having this as a dependency should not be an issue.
https://godoc.org/github.com/docker/docker/client

I'm happy to submit a PR if you like.

**Comment by ardan-bkennedy** [comment]
I rather not take the dependency for testing purposes. The cmd is working perfectly right now. I rather keep this simple. @jcbwlkr what are your thoughts?

**Comment by jcbwlkr** [comment]
Thanks for the suggestion! We are choosing to keep it simple for now. In the most recent PR that package has changed from a "docker" package to a very specific purpose tool just for database testing.

**Comment by tchaudhry91** [comment]
Fair enough. Cheers
