### ISSUE TITLE
MongoDB driver gopkg.in/mgo.v2 not supported

### ISSUE THREAD

**Issue by farrukhny** [ardanlabs/service#60]
I see we use gopkg.in/mgo.v2 which is not supported anymore i think we should consider to start using official mongodb driver for GO

https://github.com/mongodb/mongo-go-driver

**Comment by wyattjoh** [comment]
I've been using the new driver quite a bit and can say that it's a definite step up!

**Comment by catherinetcai** [comment]
If conversion is too much of a pain, would also at least suggest using [the community maintained](https://github.com/globalsign/mgo) version instead.

**Comment by ardan-bkennedy** [comment]
Hi! We are working on a version to replace Mongo with Postgres so we haven’t done the work to switch out the driver. That being said, if you have the time I would take a PR 😊

**Comment by nafisfaysal** [comment]
We use [the community maintained](https://github.com/globalsign/mgo)  MongoDB driver for Go most of our production app. I would love to see the Postgres support but not replacing the Mongo Support.

**Comment by jcbwlkr** [comment]
This is closed with the switch to postgres
