### ISSUE TITLE
Put logic around logging with expanded details

### ISSUE THREAD

**Issue by jcbwlkr** [ardanlabs/service#98]
Right now `internal/mid/errors.go` logs the errors it receives using `%+v`. If the error in question was wrapped with `pkg/errors` then it will print a stack trace.

This is good for *unexpected errors* but rather annoying for normal errors like a bad request. For example if someone tries to make a product with a quantity of -10 I don't need to see a whole stack trace.

**Comment by ardan-bkennedy** [comment]
@jcbwlkr do we still want to do something with this?

**Comment by jcbwlkr** [comment]
I think it would be worth it for you to look into it. It needs some trial
and error for expected vs unexpected errors to see if you're happy with the
output.

**Comment by ardan-bkennedy** [comment]
I am going to close this. I think this is a teachable moment in the code.
