### ISSUE TITLE
Distributed logging

### ISSUE THREAD

**Issue by shevchenkodenis** [ardanlabs/service#99]
There is a mention in readme that project contains the feature of 
* Distributed logging

but as far as I understand there is a simple logger that writes to stdout and nothing more. Do you consider to achieve distributed logging by adding some logging driver to docker-compose or another way?

**Comment by ardan-bkennedy** [comment]
Because we make sure the traceid is sent across any network request to our microservices, you are able to stitch the logs together. Where you send the logs is outside the scope of the class. All services write logs to stdout.

**Comment by shevchenkodenis** [comment]
Thanks.
